### ISSUE TITLE
trigger first load manually

### ISSUE THREAD

**Issue by mitjarobic** [PeachScript/vue-infinite-loading#103]
Can i somehow stop the first load to trigger automatically and trigger it manually?

**Comment by OBKoro1** [comment]
I also want to ask

**Comment by PeachScript** [comment]
@mitjarobic @OBKoro1 sorry for the late reply, maybe [this solution](https://github.com/PeachScript/vue-infinite-loading/pull/72#issuecomment-325465628) can help you.

**Comment by pirmax** [comment]
Same problem, but your help @PeachScript isn't longer relevant...

**Comment by wells1013** [comment]
+1

**Comment by PeachScript** [comment]
Hi @mitjarobic @OBKoro1 @pirmax @wells1013 , I have been created a documentation for this issue, you can checkout it in [here](https://peachscript.github.io/vue-infinite-loading/#!/getting-started/trigger-manually), hope it can help you.

**Comment by maxwelladapoe1** [comment]
hello please does the link above still work for manually triggering first load?

**Comment by PeachScript** [comment]
@maxwelladapoe1 oh it belongs to the old docs, I forgot to update it after I released the new docs, now it is available :)

**Comment by maxwelladapoe1** [comment]
Thanks

**Comment by mostafaznv** [comment]
I think this is a good workaround:


**Template:** 
```
<infinite-loading :distance="distance" @infinite="infiniteHandler"></infinite-loading>

<button v-if="distance < 0" @click="loadMore" />Load More</button>
```

**Script:**
```
data: () => ({
        distance: -10000, // to disable auto loading
}),
methods: {
        infiniteHandler($state) {
            if (this.hasNextPage) {
                // this function is responsible to fetch data from api 
                // and then, it call $state.loaded() or $state.complete()
                this.fetchResources($state);
            }
            else if ($state) {
                $state.complete();
            }
        },

        loadMore() {
            const doc = document.documentElement;
            const scrollTop = (window.pageYOffset || doc.scrollTop)  - (doc.clientTop || 0);

            this.distance = 100; // enable auto loading

            doc.scroll(0, scrollTop - 1); // force fire scroll event
        }
    }
```
