### ISSUE TITLE
Issue Cannot read property '_withTask' of undefined

### ISSUE THREAD

**Issue by mtibbo** [PeachScript/vue-infinite-loading#105]
### Version

2.2.1

### Vue.js version

2.5.2

### What is expected?

I expected to have the same result as the 'Basic use' of the module documentation
[https://peachscript.github.io/vue-infinite-loading/#!/getting-started/basic](url)
### What is actually happening?

The spinner doesn't disappear and the error message 'TypeError: Cannot read property '_withTask' of undefined' show up in the console of the browser (I use Chrome)

### How to reproduce this problem?

I have install the module with npm and i use webpack for compiling my application. Did i need an extra configuration in webpack for the module ?

(Sorry for my bad english, i'm french ;))

**Comment by PeachScript** [comment]
Sorry for late, I don't think this problem was caused by this component, could you provide the error stacks that output to the console of Chrome browser?

**Comment by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [comment]
I also encountered this problem, you now solve Well, if solved, is how to solve, urgent

**Comment by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [comment]
@PeachScript 
@mtibbo

**Comment by PeachScript** [comment]
@MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM it is still has not been solved, I need your help to reproduce this problem.

**Comment by tetreault** [comment]
Hey @PeachScript I just ran into this issue and saw the OP hasn't replied. I'm new to Vue so I'm sure I botched something small in some way. Here's what you requested: 

<img width="656" alt="screenshot 2018-01-06 20 31 52" src="https://user-images.githubusercontent.com/5934354/34645624-b27333c2-f320-11e7-84d8-9334ee6fc666.png">

And here is the small code sample: 

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <style>
      #effect {
        width: 100px;
        height: 100px;
        border: 1px solid black;
      }

      .highlight {
        background-color: red;
        width: 200px !important;
      }

      .shrink {
        background-color: gray;
        width: 50px !important;
      }
    </style>
  </head>
  <body>
    <div id="exercise">
      <!-- 1) Start the Effect with the Button. The Effect should alternate the "highlight" or "shrink" class on each new setInterval tick (attach respective class to the div with id "effect" below) -->
      <div>
        <button @click="startEffect">Start Effect</button>
        <div 
          id="effect"
          :class="effectClasses"
        ></div>
      </div>
      <!-- 2) Create a couple of CSS classes and attach them via the array syntax -->
      <div>I got no class :(</div>
      <!-- 3) Let the user enter a class (create some example classes) and attach it -->
      <div>
        <input type="text">
        <div></div>
      </div>
      <!-- 4) Let the user enter a class and enter true/ false for another class (create some example classes) and attach the classes -->
      <div>
        <input type="text">
        <input type="text">
        <div></div>
      </div>
      <!-- 5) Repeat 3) but now with values for styles (instead of class names). Attach the respective styles.  -->
      <div>
        <input type="text">
        <div></div>
      </div>
      <!-- 6) Create a simple progress bar with setInterval and style bindings. Start it by hitting the below button. -->
      <div>
        <button v-on:click="startProgress">Start Progress</button>
        <div></div>
      </div>
    </div>
    <script src="https://npmcdn.com/vue/dist/vue.js"></script>
    <script src="app.js"></script>
  </body>
</html>
```

```
'use-strict';

document.addEventListener('DOMContentLoaded', () => {
  const vue = new Vue({
    el: '#exercise',
    data: {
      hasEffect: false
    },
    computed: {
      effectClasses: function() {
        return {
          highlight: this.hasEffect
        };
      }
    },
    methods: {
      startEffect: function() {
        this.hasEffect = !this.hasEffect;
      }
    }
  });
});
```

**Comment by PeachScript** [comment]
@tetreault thank you very much! According to your information, I notice this demo didn't used this component but still thrown error, so I think this error may not caused by this component.

By the way, I upload your demo on the [jsfiddle](https://jsfiddle.net/u6er69gk/), you can try it, and the error has not been thrown when I create the `startProgress` function into `methods` property.

Thanks again!

**Comment by tetreault** [comment]
Thanks @PeachScript it oddly enough was something local that was th eissue on my computer. All good on my end now though!

**Comment by happyzhanls** [comment]
Thanks for the solution @PeachScript . I fixed it by adding that startProgress() method. 
But let me tell you why this thing is a little bit fucked up.
### What?
The entire code is an exercise. 
```
      <!-- 1) Start the Effect with the Button. The Effect should alternate the "highlight" or "shrink" class on each new setInterval tick (attach respective class to the div with id "effect" below) -->
      <div>
        <button @click="startEffect">Start Effect</button>
        <div 
          id="effect"
          :class="effectClasses"
        ></div>
      </div>
```
I run the code when Ass#1 is done, but get this
<img width="485" alt="capture" src="https://user-images.githubusercontent.com/23114302/36522848-f967b2d0-175b-11e8-933f-b5bb3b473934.PNG">
What is the property or method "startProgress"? Is that a built-in function of VueJS that I don't know?  

Search on Internet..............Come here..................

```
      <!-- 6) Create a simple progress bar with setInterval and style bindings. Start it by hitting the below button. -->
      <div>
        <button v-on:click="startProgress">Start Progress</button>
        <div></div>
      </div>
```
Ok, the HOLY startProcess() method is called in the DAMN Ass#6. Could have read the warn message more carefully. (Believe it or not, it takes me at least half an hour to figure out).

**Comment by zoe-zc** [comment]
@PeachScript Thank you so mush.

**Comment by MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM** [comment]
This problem is the version of VUE, the version of VUE down to the 2.3 version of the good, the 2.5 version of the revision of the VUE source of one of the attributes, forget what property, can Google query

@PeachScript

**Comment by yedidisatya** [comment]
If you are keeping empty method in the script file
or undefined event in the template it's giving "Cannot read property '_withTask' of undefined" error. I resolved this error by removing undefined events.

**Comment by incredibleXE** [comment]
@yedidisatya thanks for your comment. I would like to implement your solution. The problem is that I cannot find any empty function nor any undefined events. 

I think the problem is, that I maybe understand you wrong. Can you give me some example whats would be a wrong approach and what would be the solution?

kind regards, 
Fabian

**Comment by electrocnic** [comment]
Possible solution for other people with the same issue:

In my case I defined functions in the computed-properties section of Vue, and tried to use them FROM WITHIN a function in the methods section. This will also lead to the _withTask error. Just move the functions from your computed section to your methods section to fix this.

**Comment by Hack-Jay** [comment]
> If you are keeping empty method in the script file or undefined event in the template it's giving "Cannot read property '_withTask' of undefined" error. I resolved this error by removing undefined events.

it is work for me .

**Comment by CharlieKuharski** [comment]
> Possible solution for other people with the same issue:
> 
> In my case I defined functions in the computed-properties section of Vue, and tried to use them FROM WITHIN a function in the methods section. This will also lead to the _withTask error. Just move the functions from your computed section to your methods section to fix this.

VueJs Version :"2.5.21"
This works.  Note: you will get the _withTask error if the function is in with 'computed' or 'watch'
