### ISSUE TITLE
Filter issue on load

### ISSUE THREAD

**Issue by maki10** [PeachScript/vue-infinite-loading#106]
### Version
2.2.0

### Vue.js version
2.3.5

### How to reproduce this problem?
On load when change filter, when load is not completed, filter are dismissed. Catch in time when spinner start, change filter, then spiner end's, and add double items. How to reset that event when spinner start?

After clicking so many time on filter, they just inserting objects. How to prevent this?

https://jsfiddle.net/t0mfo5qa/

**Comment by PeachScript** [comment]
Hi @maki10 , I've tried your live demo but it doesn't work, even though I have imported `Vue.js` and this component manually. Could you provide a MVP(Minimum Viable Program)?

**Comment by maki10** [comment]
Yes, because is calling php server behind to get request, easiest way to test is on your's example from website to add button instead of dropbox, and give a shot. 
I fix this with simple `bouncer`  https://stackoverflow.com/a/1909508/3740460

**Comment by PeachScript** [comment]
Got it! Now this problem has been solved, so I will close this issue.

Best regards.
