### ISSUE TITLE
spinner show only when isLoading === true?

### ISSUE THREAD

**Issue by cfabregas** [PeachScript/vue-infinite-loading#107]
In your demo I niticed that the spinner will be hide only when isComplete === true, that makes your demo much smoother.
Do I have any access to modify it? 
Thanks!

**Comment by PeachScript** [comment]
Nope, same as the title of your issue, the spinner show only when the `isLoading` is true([source code](https://github.com/PeachScript/vue-infinite-loading/blob/master/src/components/InfiniteLoading.vue#L3), and when you `complete` this component, the `isLoading` will be set to false([source code](https://github.com/PeachScript/vue-infinite-loading/blob/master/src/components/InfiniteLoading.vue#L143)), so the spinner will hide.

**Comment by cfabregas** [comment]
@PeachScript 
Thanks for your reply! 
But it doesn't make sense. In your demo, when i scroll the page to the bottom, the spinner is shown immediately like it never have been hide. However when I scroll in my own project, I found it clearly takes a little time to render the spinner, that makes the page lag.

**Comment by PeachScript** [comment]
Sounds like the spinner is shown too late, does the `distance` property can help you?

**Comment by PeachScript** [comment]
Oh sorry, I think this problem is caused by the debounce logic, in order to avoid calculate distance multiple times in a short time, source code is [here](https://github.com/PeachScript/vue-infinite-loading/blob/master/src/components/InfiniteLoading.vue#L121). You can modify the debounce time through this:
```js
this.$refs.infiniteLoading. debounceDuration = 10; // unit: ms
```

**Comment by cfabregas** [comment]
@PeachScript 
modified `distance` doesn't make any difference, but the shorter `debounceDuration` do helps.
Really delighted!
谢谢大神
