### ISSUE TITLE
infiniteHandler($state)的$state为空。

### ISSUE THREAD

**Issue by klausgao** [PeachScript/vue-infinite-loading#109]
### Version
2.2.1

### Vue.js version
2.4

### What is expected?
infiniteHandler($state) {
   console.dir($state);
}
第一次加载的时候是正常的，第二次console就是undefined了。

### How to reproduce this problem?

我现在的临时解决方案是在vue的data里放一个变量来保存这个$state。

**Comment by klausgao** [comment]
不行，从第一次调用就获取不到$state，现在用旧的写法就ok了

**Comment by PeachScript** [comment]
模板中的 `infinite` 事件绑定的写法是怎样的？

**Comment by PeachScript** [comment]
No updates, I will close this issue, you can reopen it if you need in the future.

**Comment by feverbit** [comment]
他问的可能是手动调用infiniteHandler($state)的时候，$state如何传入，比如单页切换tab的时候。
看了源代码，需要两点：
1.<infinite-loading @infinite="infiniteHandler" ref="infiniteLoading"  spinner="waveDots"></infinite-loading>，配置ref
2.      this.infiniteHandler(this.$refs.infiniteLoading.stateChanger);
源代码里面stateChanger封装了3种行为，直接从$ref获取，按照上面就可以了。
