### ISSUE TITLE
Infinite scroll triggering  continuously out of controll

### ISSUE THREAD

**Issue by Nagasir** [PeachScript/vue-infinite-loading#114]
### Version
2.2.2

### Vue.js version
2.5

### What is expected?
Trigger at first load and trigger again only when user scrolls

### What is actually happening?
Triggering continuously at first load until the end of data, so my Y scroll become so height

### How to reproduce this problem?
Add this css
```
body {
     overflow-y: scroll;
}
```

Btw, I'm keeping `overflow-y: scroll;` on the body to prevent screen blinking when resetting infinite scroll data.

**Comment by PeachScript** [comment]
If your `body` element is not the real scroll wrapper element, you can add the `force-use-infinite-wrapper` attribute to force use `window` element or other element which has `infinite-wrapper` attribute as the scroll wrapper, it's a workaround :)

**Comment by Nagasir** [comment]
Unfortunately, I'm using the `body ` as the scroll parent element.

**Comment by PeachScript** [comment]
@Nagasir got it, I will fix it recently.

**Comment by PeachScript** [comment]
Hello @Nagasir , I have been released a new version [v2.2.3](https://github.com/PeachScript/vue-infinite-loading/releases/tag/v2.2.3) to try to fix this problem, you can try it now, if it still now working, please tell me, thanks!

**Comment by Nagasir** [comment]
Yes it is fixed, thank you very much!

**Comment by svewag** [comment]
@PeachScript thx for the great work! Does this also fix https://github.com/PeachScript/vue-infinite-loading/issues/114 ?
