### ISSUE TITLE
Infinite scroll triggering stuck in a loop

### ISSUE THREAD

**Issue by Isa79** [PeachScript/vue-infinite-loading#116]
### Version
2.2.3

### Vue.js version
2.5.5

### What is expected?
It should trigger when scrolling a distance

### What is actually happening?
It's stuck in a loop. Triggers when opening the page. Not when scrolling.

### How to reproduce this problem?
Just follow the hackersnews tutorial. I had to also wrap it in `    <div infinite-wrapper>` since it gave me an error. But thats about it.

**Comment by PeachScript** [comment]
Does the `div` element has `overflow: auto | scroll` and `height` or `max-height`?

**Comment by Isa79** [comment]
@PeachScript dont think so. using it with vuetify. 

```
    <div infinite-wrapper>
      <v-layout row wrap>
        <Item v-for="(item, i) in item" :key="i" />
        <infinite-loading force-use-infinite-wrapper="true" @infinite="infiniteHandler">
        </infinite-loading>
      </v-layout>
    </div>
```

**Comment by PeachScript** [comment]
@Isa79 the scroll wrapper element must be scrollable and has fixed height or maximum height, how about the `div` element?

**Comment by Isa79** [comment]
@PeachScript It somehow works now. What I did was remove the infinite-wrapper and just wrap it in a div element.

```
    <div>
      <v-layout row wrap>
        <Item v-for="(item, i) in items" :key="i" />
        <infinite-loading @infinite="infiniteHandler">
        </infinite-loading>
      </v-layout>
    </div>
```

**Comment by PeachScript** [comment]
@Isa79 so the `window` element is the real scroll wrapper element, is that right?

**Comment by hartmut-co-uk** [comment]
Note: When using with _Element_ (http://element.eleme.io/) and experiencing a loop / infinite-loading triggered until completed on page-load
-> watch out for `<el-main>` `.el-main` - which has `overflow: auto`

I may need to do more properly - but as a first quick fix following prevented the loop -> as registering event on `window` as the _scrollParent_.. :
```
  .el-main
    overflow initial !important
```
