### ISSUE TITLE
Reset becoming a function also?

### ISSUE THREAD

**Issue by garhbod** [PeachScript/vue-infinite-loading#123]
Hi,

I'm currently using reset as follows as
```
this.$refs.infiniteLoading.$emit('$InfiniteLoading:reset');
```

Is there plans to create a `reset()` function or exposing the `$state` when I use `$refs` making one of the following 2 possible
```
this.$refs.infiniteLoading.reset();
this.$refs.infiniteLoading.$state().reset();
```

**Comment by garhbod** [comment]
Also a side note the drop down on your docs for the version needs to have a different text colour as it is white on white at the moment

**Comment by PeachScript** [comment]
Hi @garhbod ,there has a special property on the `InfiniteLoading` component, you can use `this.$refs.infiniteLoading.stateChanger.reset()` to access the `reset` function, the `$state` parameter is actually `stateChanger` property.

**Comment by PeachScript** [comment]
For your second comment,  could you paste a screenshot here?

**Comment by garhbod** [comment]
![image](https://user-images.githubusercontent.com/4616198/34860632-aad68022-f7aa-11e7-81a6-5fc87e3e6a37.png)

**Comment by PeachScript** [comment]
Thanks! I guess it is related to browser or OS, which browser and OS are you using?

**Comment by garhbod** [comment]
Chrome on windows
________________________________

**Comment by PeachScript** [comment]
Okay, I will fix it in the near future.

**Comment by PeachScript** [comment]
The color problem has been fixed :)
