### ISSUE TITLE
How to track window Scroll is in what Item Component?

### ISSUE THREAD

**Issue by feedgit** [PeachScript/vue-infinite-loading#124]
Hello,

Im finding a solution for my Music Website to track window Scroll is in what Item Component in order I can write a function: When people scroll to any song. they can **press Play by use Spacebar instead** click to play button.

Can I make it?

**Comment by PeachScript** [comment]
Sorry, this issue has nothing to do with this component, I think you should ask it on the StackOverflow, is that right?
