### ISSUE TITLE
How can i use $state outside the @inifinite callback function?

### ISSUE THREAD

**Issue by elieandraos** [PeachScript/vue-infinite-loading#125]
Hi guys, great plugin !
How can i use $state outside the @inifinite callback function?
actually i need to do $state.reset() from a watch property change.
I managed to do that with `this.$refs['infiniteLoading'].$emit('$InfiniteLoading:reset');` but not with the $state as it is undefined in the watcher.

**Comment by PeachScript** [comment]
Sure, https://github.com/PeachScript/vue-infinite-loading/issues/123#issuecomment-357129636

**Comment by PeachScript** [comment]
And glad you like it :P
