### ISSUE TITLE
Cannot read property '$emit' of undefined"

### ISSUE THREAD

**Issue by AlexVFornazieri** [PeachScript/vue-infinite-loading#126]
How I loved this plugin! ;)
But I believe we have a small bug, or the example in the documentation was not properly updated according to the latest version.

Version: 2.2.3 --- Vue.js version: 2.5.13

### What is expected?
No error in log, state reseted

### What is actually happening?
[Vue warn]: Error in nextTick: "TypeError: Cannot read property '$emit' of undefined"

### How to reproduce this problem?
Calling a 'changeFilter' method after filter props was changed, like example in docs

```
changeFilter() {
      this.$nextTick(() => {
        this.$refs.infiniteLoading.$emit("$InfiniteLoading:reset");
      });
}
```

**Comment by PeachScript** [comment]
Did you forgot to set `ref`  for the `InfiniteLoading` element?

```
<infinite-loading ref="infiniteLoading"></infinite-loading>
```

**Comment by AlexVFornazieri** [comment]
Is it! My fault, thanks for help, great job, this plugin is awesome!

**Comment by PeachScript** [comment]
You're welcome, glad you like it :P
