### ISSUE TITLE
没上拉就开始刷新了

### ISSUE THREAD

**Issue by wsygdiv** [PeachScript/vue-infinite-loading#128]
### Version
最新版本

### Vue.js version
最新

### What is expected?
刷新页面，@infinite="infiniteHandler0($event)"方法就开始执行，而且报错```
[Vue-infinite-loading error]: executed the callback function more than 10 times for a short time, it looks like searched a wrong scroll wrapper that doest not has fixed height or maximum height, please check it. If you want to force to set a element as scroll wrapper ranther than automatic searching, you can do this:

<div infinite-wrapper>
  ...
  
  <infinite-loading force-use-infinite-wrapper="true"></infinite-loading>
</div>
```

### What is actually happening?


### How to reproduce this problem?
帮忙看一下

**Comment by PeachScript** [comment]
文档中有 `top` 方向的使用提示：

![image](https://user-images.githubusercontent.com/5035925/35605503-0da76d82-0684-11e8-9007-041488181dc9.png)

**Comment by wsygdiv** [comment]
找到原因了
