### ISSUE TITLE
TypeError: Cannot read property 'loaded' of undefined on buefy tabs

### ISSUE THREAD

**Issue by rizqyhi** [PeachScript/vue-infinite-loading#129]
### Version
2.2.3

### Vue.js version
2.5.3

### What is expected?
The component should work as in the demo.

### What is actually happening?
The spinner is not showing, the component rendered after the data loaded. Also the $state is return undefined, resulting the following error when loaded is called.
```TypeError: Cannot read property 'loaded' of undefined```

### How to reproduce this problem?
I am using [Buefy's tabs](https://buefy.github.io/#/documentation/tabs) to create my interface. The library working well when I placed it in first tab. However it doesn't work when the tab is not first active.

I've tried hooking the tab change event and trigger the manual load attempt. It also didn't work.

**Comment by PeachScript** [comment]
Could you provide a live demo?

**Comment by rizqyhi** [comment]
Check here please: https://jsfiddle.net/rizqyhi/4qr9806f/3/

**Comment by PeachScript** [comment]
Because the `Buefy` tab component has transition effect, so we have to wait for transition to finish then trigger the `attemptLoad` method, usually, we just need to listen `transitionend` event of all tabs except the first one, and only listen once time.

I have updated your live demo to implement it, hope this demo can help you: https://jsfiddle.net/4qr9806f/4/

**Comment by rizqyhi** [comment]
Hello, thank your for your solution. I've updated my project and it works. However, I got a new problem when it goes with vue-router. The `transitionend` won't fire after I push new page with `$router.push()` programmatically. I also tested with `<router-link>` and it works.

The updated demo with vue-router: https://jsfiddle.net/rizqyhi/4qr9806f/7/

**Comment by PeachScript** [comment]
Aha, I have been tested your demo with Chrome 63, and it works, even if use `$router.push`, this is the updated demo: https://jsfiddle.net/4qr9806f/8/

**Comment by rizqyhi** [comment]
It seems still not working on me, using Chrome 64. Did you try to click the content on tab 2?
It appears the issue occurs only after I click the content inside.

**Comment by PeachScript** [comment]
I tried it just now, but when I remove `infinite-loading` component, your problem still exists, so it looks like not related to this component, you can report your problem to `vue-router` or `Buefy`.

**Comment by rizqyhi** [comment]
Ok, got it. The issue is `transitionend` event isn't fired. I'll try to open this issue on them. Thank you.

**Comment by PeachScript** [comment]
You're welcome :).

**Comment by cwilby** [comment]
A workaround I'm using for this:

```vue
<template>
  <b-tab v-model="activeTab">
    <b-tab-item label="Sprockets">
      ...
      <vue-infinite-loading ... v-if="activeTab === 0" />
    </b-tab-item>
    <b-tab-item label="Ratchets">
      ...
      <vue-infinite-loading ... v-if="activeTab === 1" />
    </b-tab-item>
  </b-tab>
</template>

<script>
export default {
  ...

  data: () => ({
    activeTab: 0
  })
  
  ...
};
</script>
```
