### ISSUE TITLE
About loading results problem.

### ISSUE THREAD

**Issue by zhaozhe0831** [PeachScript/vue-infinite-loading#130]
### Version
vue-infinite-loading: 2.2.3

### Vue.js version
vue: 2.5.9

### What is expected?
![image](https://user-images.githubusercontent.com/12945873/35665547-b52ee34a-0761-11e8-86b6-53a16a22d6be.png)

If I load all of data on the first loading, it shows no-results. But it should show no-more.
I just can speak a little English.

**Comment by PeachScript** [comment]
If you have been called the `$state.loaded` before `$state.complete`, this component will display the `no-more` message, so I think you should check your source code and make sure it calls the `$state.loaded` and the `$state.complete` correctly, it will looks like this:

```js
...
infiniteHandler($state) {
  ajax(...).then((res) => {
    if (res.data.length) {
      $state.loaded();
      if (!res.next) { // or res.totalPage === res.currentPage
        $state.complete();
      }
    } else {
      $state.complete();
    }
  });
}
...
```

**Comment by zhaozhe0831** [comment]
Thank you @PeachScript . I think it's useful.

**Comment by PeachScript** [comment]
You're welcome :)
