### ISSUE TITLE
Event "infinite" not fired when scroll event not stopped

### ISSUE THREAD

**Issue by vgladimir** [PeachScript/vue-infinite-loading#132]
### Version
2.2.3

### Vue.js version
2.5.13

### What is expected?
When I scroll down it must make "Load more" action. When I used 2.1.3 all was okey.

### What is actually happening?
Event `infinite` not fired when scroll event not stopped

### How to reproduce this problem?
![2018-02-03 12_30_29](https://user-images.githubusercontent.com/19341468/35766287-1193c7e0-08de-11e8-84a3-fb965addf372.gif)

**Comment by PeachScript** [comment]
Could you provide a live demo?

**Comment by vgladimir** [comment]
Currently it is not possible. Difference with your example is that your list don't have Apple's "bounce" effect. When I used 2.1.3 all was okey.

**Comment by PeachScript** [comment]
Hi @vgladimir , is this problem still exists?
