### ISSUE TITLE
用element的表格 ui 会出现一直触发加载

### ISSUE THREAD

**Issue by wYuanHpp** [PeachScript/vue-infinite-loading#133]
### Version

 最新
### Vue.js version

3.0.1
### What is actually happening?
开头两次加载还正常,之后会变成无限触发加载,我看了一下原因,是应为触发加载后并且渲染完成后,滚动条没有像预期的那样向上跳一段,而是直接顶到底,致使加载组件一直出现在窗口上,这样导致组件不停触发事件,这个有解决办法么?

**Comment by PeachScript** [comment]
如果 direction 是 top，需要手动处理 `scrollTop` 的变更：

![](https://user-images.githubusercontent.com/5035925/35605503-0da76d82-0684-11e8-9007-041488181dc9.png)

**Comment by wYuanHpp** [comment]
不是的 ,我是设成 bottom 的 ,但是出现的情况确实是设为 top 时出现的问题

**Comment by PeachScript** [comment]
请提供一个重现问题的 live demo

**Comment by zhangbg** [comment]
@PeachScript 个人也遇到类似的问题，具体场景是滚动条在body元素下， 建议你提供个独立的页面的DEMO。

**Comment by Lin-YingYu** [comment]
加载组件versoin: ^2.3.1
我这边也有这样的情况：
1、迅速滑动到底部,加载组件会不挺触发infinite事件。
2、滚动条滑动到底部，此时重新刷新页面（滚动条一直存在底部）会一直触发infinite事件加载。
`<template>
  <div class="cashHistory">
    <ul class="record" v-cloak>
      <li class="record-item" :key="index" v-for="(item, index) in integralHistoryList">
        <div class="left">
          <p class="record-detail">{{ item.type }}</p>
          <p class="record-time">{{ item.time | FriendlyTime }}</p>
        </div>
        <div class="right">{{ item.flag === 0 ? '+' : '-' }}{{ item.point }}金币</div>
      </li>
    </ul>
    
      <infinite-loading @infinite="infiniteHandler">
        <span slot="no-results">
          已经展示完毕咯
        </span>
        <span slot="no-more">
          已经展示完毕咯
        </span>
      </infinite-loading>
    
  </div>
</template>
<script>
import InfiniteLoading from 'vue-infinite-loading';
import { getJbHistory } from '../api';

export default {
  name: 'cashHistory',
  props: {
    uid: {
      type: Number,
    },
  },
  data() {
    return {
      page: 0,
      left: 0,
      integralHistoryList: [],
    };
  },
  methods: {
    // 获取金币历史记录
    async getJbHistory($state) {
      try {
        this.page += 1;
        const len = this.integralHistoryList.length;
        if (len) {
          const flag = this.integralHistoryList[len - 1].flag;
          this.left = flag === 1 ? (this.integralHistoryList[len - 1].left - this.integralHistoryList[len - 1].point) :
            (this.integralHistoryList[len - 1].left + this.integralHistoryList[len - 1].point);
        }
        const res = await getJbHistory(this, { uid: this.uid, page: this.page, left: this.left });
        if (res.error_code === 1) {
          if (res.data.integralHistoryList.length) {
            this.integralHistoryList = this.integralHistoryList.concat(res.data.integralHistoryList);
            $state.loaded();
          } else {
            $state.complete();
          }
        } else {
          this.toast(res.msg);
          $state.complete();
        }
      } catch (error) {
        this.toast('网络错误~');
        $state.complete();
      }
    },
    infiniteHandler($state) {
      this.getJbHistory($state);
    },
    // toast 轻提示
    toast(text) {
      this.$toasted.show(text, {
        theme: 'primary',
        position: 'top-center',
        duration: 2000,
      });
    },
  },
  components: {
    InfiniteLoading,
  },
};
</script>
<style lang="scss" scoped>
.pull-loading {
  background-color: #F2F2F2;
}
</style>
`

**Comment by aiddroid** [comment]
同样的问题，elementUI，默认配置，停留在list底部的时候，真的成了infinite loading,一直重复触发，卡死浏览器。

**Comment by PeachScript** [comment]
@aiddroid 你的 `loadMore` 方法中没有对列表数据做追加，致使滚动条长度没发生变化，插件会认为容器内没有填充足够的数据，『一直重复触发』正是预期结果。

**Comment by PeachScript** [comment]
这里是配合 ElementUI 卡片组件的 live demo：http://jsfiddle.net/h0Lt3b9s/ 。

如果各位在使用的时候仍然遇到问题，请 fork 此 demo 进行重现并贴出地址，以便分析问题产生的原因。

**Comment by Dragon-Rider** [comment]
https://jsfiddle.net/a7x5zdr7/19/
@PeachScript 
您好，请问这个demo是什么问题呢？我发现删除css里的任一行，loading组件能够正常运行。

 div {
  width: 49%;
  box-sizing: border-box;
  padding: 0 20px;
}

**Comment by PeachScript** [comment]
各位，关于如何与 Element UI 的表格组件一起使用，新版文档中已经已经给出了[使用示例](https://peachscript.github.io/vue-infinite-loading/guide/use-with-el-table.html)，以作参考。

此 issue 先行关闭，如果在使用过程中遇到问题，请继续在此进行讨论；如果遇到的是其他问题，请另开 issue 进行讨论。
