### ISSUE TITLE
Component not triggered if not in view

### ISSUE THREAD

**Issue by abishekrsrikaanth** [PeachScript/vue-infinite-loading#134]
### Version
2.2.3

### Vue.js version
2.1.10

### What is expected?
When a list that is configured with the `vue-infinite-loading` is not in view, then the component is not triggered.

### What is actually happening?
I use the bootstrap tab and on each tab there is a table that is configured to individual `vue-infinite-loading` component. If the tab isn't active, then the component is not triggered.

How do I go about loading the table on a tab that isn't active

**Comment by PeachScript** [comment]
You can try `this.$refs.infiniteLoading.attemptLoad` method to trigger load manually after tab switched.

Maybe I should add a event to support that, how do you think?

**Comment by abishekrsrikaanth** [comment]
yes, an event will be great, but is there a way to load them without having to bring them to view.

Here is my use-case. I have a common filter for the data that needs to be loaded on both tabs. And I load both the tabs based on the filter selections and also update the count on the tab selector. Currently this doesn't work if I call `this.$refs.infiniteLoading.attemptLoad` manually on `mounted`

![capto_capture 2018-02-12_10-31-10_am](https://user-images.githubusercontent.com/1639302/36104454-1165e8e4-0fe0-11e8-9c37-ac517c3781fd.png)

Appreciate if you can help me on this at the earliest.

**Comment by abishekrsrikaanth** [comment]
@PeachScript Do you have any suggestions on how to implement this?

**Comment by abishekrsrikaanth** [comment]
@PeachScript any updates on this?

**Comment by PeachScript** [comment]
Sorry for late, it is a special case, I will consider it carefully, thanks.

For now, you can extends a new Component from this component, and override the attemptLoad method to remove [this line](https://github.com/PeachScript/vue-infinite-loading/blob/master/src/components/InfiniteLoading.vue#L214).

**Comment by aleksanderd** [comment]
+1
any updates?

**Comment by aleksanderd** [comment]
one more way to make it working without overriding/hacking infinite component.
```js
mounted () {
  this.$refs.infinite.isLoading = true // to avoid duplicate(normal) request if "we visible"
  this.loadMore(this.$refs.infinite.stateChanger)
}
```
where loadMore is callback onInfinity
what you think?

**Comment by PeachScript** [comment]
Hi @abishekrsrikaanth @aleksanderd , this issue has been on hold for long time, I'm so sorry.

I've considered it carefully, and made two opinions:

1. The scroll distance logic depends on the `getBoundingClientRect` API but it cannot works for an off-screen element, so it will be too complex if implement the `allowLoadingIfInvisible` feature;
2. From the user experience perspective, if we want to preload some data for users, we should prepare it directly rather than via a infinite scroll component because the scroll container is invisible for users.

So I think we can implement it like this:

``` js
export default {
  /* ... */
  mounted() {
    // preload the first page of data for users
    this.infiniteHandler();
  },
  methods: {
    infiniteHandler($state = { loaded() {}, complete() {} }) {
      /* logic to request and fill up data */
    },
  },
};
```

How do you think about it?

**Comment by zek** [comment]
Any news for this? I am using nuxt and component is invisible under a dropdown menu. I cant use ref solution.

I need to set also state because if 1 page is loaded and I try to load next page "No results" is shown

**Comment by PeachScript** [comment]
Hi @zek , could you explain why the infinite list be in a dropdown menu? I want to know the details of your situation.

**Comment by Goldbeener** [comment]
same case , here is my solution for reference： 
```vue
<template>
  <infinite-loading v-if="isVisible" ...>
   
  </infinite-loading>
</template>


<script>
  export default {
    /* ... */
    data(){
       isVisible: false,
    },
    mounted() {
      const self = this;
      const intersectionObserver = new IntersectionObserver(function(entries) {
          if (entries[0].intersectionRatio <= 0) return;
          // present
          self.isVisible = true;
      });
      intersectionObserver.observe(document.querySelector(target));
    },
  };
</script>
```
