### ISSUE TITLE
how to set property to top

### ISSUE THREAD

**Issue by crystof5** [PeachScript/vue-infinite-loading#137]
Hi!
 i want to implement this pluging for chat, so i need to load only when i scroll to top. i'm not sure how can i do that ..
because with this code that don't stop to load (i have scroll bottom by default)
my code:
 <infinite-loading  @infinite="infiniteHandler" ref="infiniteLoading"> </infinite-loading>
            < div v-for="m in messages" class="row mess-body" >
               {{m}}
           < /div >
 < /infinite-loading >

and my methods:

    infiniteHandler ($state) {
      console.log('testcseroll')
      if (this.messages.length > 20) {
        console.log('testcseroll')
        axios({
          method: 'get',
          headers: {'Authorization': this.test},
          url: `http://localhost:3000/api/getMessages/${this.gameChannelID}/${this.messages[0]._id}`,
          contentType: 'application/json; charset=utf-8',
          dataType: 'json'
        }).then((response) => {
          if (response.data.length) {
            this.populateMoreMessages(response.data)
            $state.loaded()
          } else {
            $state.completed()
          }
        }).catch(() => {
        })
      }
    }

can you help me please?
Thank's a lot and sorry for my poor english

**Comment by thezachcannon** [comment]
Having same issue...Following for help.

**Comment by PeachScript** [comment]
@thezachcannon is right, duplicate with #73 , closed.
