### ISSUE TITLE
麻烦更新文档

### ISSUE THREAD

**Issue by skyshirt** [PeachScript/vue-infinite-loading#138]
希望把这个属性force-use-infinite-wrapper放到你的文档中

**Comment by PeachScript** [comment]
@skyshirt 谢谢，我会尽快添加

**Comment by Reshared** [comment]
这个属性是做什么的呀？
我现在照文档做了一遍，无法触发load，是为什么呀，跟这个有关系么

**Comment by PeachScript** [comment]
@skyshirt @Reshared 抱歉文档需要重构，所以花了比较长的时间，该属性已经添加到新版文档中，[点击查看](https://peachscript.github.io/vue-infinite-loading/api/#forceuseinfinitewrapper)。

如有任何问题请在此反馈。
