### ISSUE TITLE
TypeScript definition?

### ISSUE THREAD

**Issue by phil-scott-78** [PeachScript/vue-infinite-loading#139]
### Version
2.2.x

### Vue.js version
2.5

### What is expected?
Use component from a TS project
### What is actually happening?
Compile error due to lack of definition file.
### How to reproduce this problem?

Any thoughts on adding a typescript definition file?  I've thrown one together that gets things working for me. I think for ease of use and maintenance it makes the most sense to live with this project, but I could also submit it to the @types organization. Here's the "works for me" version I put together

``` ts
// Type definitions for vue-infinite-loading v2.2.0
// Project: https://github.com/PeachScript/vue-infinite-loading
// Definitions by: Phil Scott <https://github.com/enkafan/>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

declare module "vue-infinite-loading"  {
    import Vue from 'vue'

    export default class InfiniteLoading extends Vue{
        distance: number;
        onInfinite: Function;
        spinner: string;
        direction: string;
        forceUseInfiniteWrapper: boolean;
    }

    export interface StateChanger {
        loaded(): void;
        complete(): void;
        reset(): void;
    }
}
```

**Comment by PeachScript** [comment]
Great work! Thank you very much, I will add definition file in the next version 👍

**Comment by PeachScript** [comment]
Hi @phil-scott-78 , I have been added the [TypeScript declaration file](https://github.com/PeachScript/vue-infinite-loading/blob/master/types/index.d.ts) and released a new version [v2.3.1](https://github.com/PeachScript/vue-infinite-loading/releases/tag/v2.3.1) for it, you can try it now, thank you again :D

**Comment by phil-scott-78** [comment]
Awesome, I'll see if I can't find time to kick the tires tomorrow

**Comment by phil-scott-78** [comment]
Pulled it down. Had to make a slight change in my import, but this will get it done 👍 

Going to close the issue and thanks again!

**Comment by hartmut-co-uk** [comment]
Hi @phil-scott-78 what did you change for the import? 
Have you got it working with TS + SSR by any chance?

**Comment by phil-scott-78** [comment]
I'm not working with SSR myself, but I can tell you the trick for me to get it working was turning on `allowSyntheticDefaultImports`. Not a huge fan of having to do that, but it is enabled by default with the `vue-cli`'s template so I suspect that it's only a matter of time before I discovered another type def that would also require it.

Once that's enabled to import I'm simply doing

```
import InfiniteLoading from 'vue-infinite-loading';
```

`InfiniteLoading` is a namespace so you can then use `InfiniteLoading.StateChanger` and `InfiniteLoading.Slots` to refer to those respective types.

**Comment by hartmut-co-uk** [comment]
Hi, thanks - that's not been the same issue I was facing. 

Anyway to leave some reference... I'm on a nuxt project - and the simplest way to have it working with SSR was via nuxt 'native' `<no-ssr>`:

```
    <no-ssr>
      <infinite-loading @infinite="onInfinite" :distance="200" spinner="waveDots"></infinite-loading>
    </no-ssr>
```

working fine with default `import InfiniteLoading from 'vue-infinite-loading'` - and does _not_ require `less-loader` (https://peachscript.github.io/vue-infinite-loading/#!/getting-started/server-side-rendering)

**Comment by PeachScript** [comment]
@hartmut-co-uk that's great! I think I should add your solution to the docs, it is the best practice, is that right?

**Comment by hartmut-co-uk** [comment]
@PeachScript I think so - haven't had much time to actively work with it in this setup - so wouldn't vouch for... ;-)
