### ISSUE TITLE
Multiple infinite loading instances

### ISSUE THREAD

**Issue by duyhung85** [PeachScript/vue-infinite-loading#14]
Hi,

I have 2 list of items on the same page. Is there anyway I can use vue-infinite-loading on multiple instances?

Thanks,
Hungnd

**Comment by PeachScript** [comment]
I was late, l'm sorry.

The key point is passing event for the multiple components, all right?

You can use the ref official directive to get the instance of every component and emit event by it, to passing event for your specific component.

Hope can help you!

**Comment by PeachScript** [comment]
A week passed and no reply, I will close the issue, you can reopen it if you need. @duyhung85
