### ISSUE TITLE
Customize Loading Components

### ISSUE THREAD

**Issue by feedgit** [PeachScript/vue-infinite-loading#140]
Hello, I want to customize Loading Components with this package: https://lucasleandro1204.github.io/vue-content-loading/.

How can I do this?

**Comment by PeachScript** [comment]
You can use the `spinner` slot, insert your loading element through the slot feature of Vue.js. And it would be better if you read the [documentation](https://peachscript.github.io/vue-infinite-loading/#!/slots) before create an issue.

**Comment by feedgit** [comment]
Thank you!
