### ISSUE TITLE
@infiniteHandler fires off on page load - how do I prevent default?

### ISSUE THREAD

**Issue by cassandradanger** [PeachScript/vue-infinite-loading#142]
### Version
2.2.3

### Vue.js version
2.8.2

### What is expected?
When the page loads, the variable, pageCount is set to 10, but the infiniteHandler method fires off right away and the number increases by 10 (per the function), so instead of loading 10 results at first, it loads 20.

I would expect the infiniteHandler method to only get called upon scrolling to the bottom of the page. I tried doing something like 
`<infinite-loading @infinite.prevent="infiniteHandler">`
but that doesn't work.

`pageCount: 10,
pageCountDefined: 10,`

```
infiniteHandler($state) {
	if(this.infiniteScroll !== 'stop'){
		setTimeout(() => {
			this.pageCount = this.pageCount + this.pageCountDefined;
			this.refreshParts();
			$state.loaded();
		}, 1000);
	} else {
		$state.complete();
	}
},
```

**Comment by PeachScript** [comment]
Hi @cassandradanger , the `prevent` modifier only can be used with native event, the `infinite` is a custom event, so it cannot work properly.

This component will trigger continuously until the scroll wrapper has scroll bar, so if you want to fill up data manually in the first time, you can render this component after the scroll wrapper be fill up through `v-if` directive:

```html
<infinite-loading v-if="pageCount > 10"></infinite-loading>
```

**Comment by cassandradanger** [comment]
Doing that v-if prevents the infiniteHandler from triggering at all. I'm just trying to prevent it from triggering on page load

**Comment by cassandradanger** [comment]
So, would there be 2 instances of the infinite-loading component?

```
<infinite-loading @infinite="infiniteHandler" spinner="spiral">
			<span slot="no-more">
			There are no more parts.
			</span>
		</infinite-loading>
		<infinite-loading v-if="pageCount > 10"></infinite-loading>
```

**Comment by cassandradanger** [comment]
It does seem to prevent the loading problem, but then I'm left with 2 instances of the infinite-loader
![capture](https://user-images.githubusercontent.com/10237149/38566861-5fe24f0c-3caa-11e8-94f5-b5e7e021ddeb.JPG)

**Comment by PeachScript** [comment]
Nope, there should be only 1 instance, perhaps I misunderstood what you mean, it would be better if you could describe your situation in detail.

**Comment by cassandradanger** [comment]
I changed the distance and it seemed to help a little bit
