### ISSUE TITLE
this.$refs.infiniteLoading.$emit('$InfiniteLoading:reset') - doesn't seem to reset $state.complete

### ISSUE THREAD

**Issue by cassandradanger** [PeachScript/vue-infinite-loading#143]
Version
2.2.3

Vue.js version
2.8.2

### What is expected?
when using  `this.$refs.infiniteLoading.$emit('$InfiniteLoading:reset');` I would expect it to reset the state of the infinite loader, but that doesn't seem to be the case.

### What is actually happening?
If you reach the bottom of the list (which means that` $state.completed()` has been called), the scroll shows that there are no items left, but if you switch to search (or vice versa) the infinite scroll doesn't reset (which is needed to call the API to get the next page of items).  So it will only show the first page of items instead of firing off the infiniteHandler action to called the next page.

limited screen recording: http://recordit.co/EGQX0duEhP

**Comment by PeachScript** [comment]
In your application, I think you can execute `this.$refs.infiniteLoading.$emit('$InfiniteLoading:reset');` and empty your list in the `@change` event handler of the search input, add debounce be better.

**Comment by josteph** [comment]
I'm also having the same issue here. Added the `@change` attribute to input with 

```
this.$refs.infiniteLoading.$emit('$InfiniteLoading:reset'); 
this.list = []
```
It doesn't seem to reset the handler. (It does empty the list but it doesn't trigger the re-fetching data which is expected behaviour).

**Comment by cassandradanger** [comment]
Interesting! That is what I was doing before, but went back to the code today and now it's working :) I guess the code and I just needed a weekend of sleep and to just let other's know we were having troubles, haha ;)
Thank you!

**Comment by PeachScript** [comment]
@cassandradanger haha, you're welcome! What a naughty code :D

**Comment by josteph** [comment]
@PeachScript Hmm I can't seem to receive `this` (vue instance) when working with lodash debounce.

```
infiniteHandler: _.debounce(($state) => {
    console.log(this) // undefined
}, 1000)
```

The example readme is using setTimeout which is not what we really expect it to be.

**Comment by PeachScript** [comment]
@josteph all right, official docs also uses `function() {}`: https://vuejs.org/v2/guide/computed.html#Watchers
