### ISSUE TITLE
An infinite event trigger in `mounted hook` 

### ISSUE THREAD

**Issue by AlexanderSkrypnyk** [PeachScript/vue-infinite-loading#145]
### What is actually happening? 

When i load a page at first i get a list of 1st 20 items from DB(offset = 0). As i understand infinite scroll event should trigger only when i reach bottom. But it triggering on `mounted hook` also. So i can't pass offset to get next items
How can i make infinite event not trigger in  `mounted hook`? Because there i fetch basic data with offset = 0. (1st 20 items )

thank you!!

**Comment by PeachScript** [comment]
Did you want to fetch 1st 20 items manually rather than through the infinite event handler?

**Comment by AlexanderSkrypnyk** [comment]
yes. I found  solution for me. I initialize component with offset =0, then i make this:
`infiniteHandler($state) {
      console.log($state)
      this.getVideosList($state, this.offset++);

 }`

**Comment by AlexanderSkrypnyk** [comment]
>
