### ISSUE TITLE
data not loading on router.push

### ISSUE THREAD

**Issue by umardraz** [PeachScript/vue-infinite-loading#146]
Hi

I need a little help to understand why one of my router.push not working as per my requirement.

I have a search box and on submit I am using router.push and then sending the search box value as keyword here is the example.

The first router.push works fine. But on the second time if I search something else then the url is updating correctly but the data is not updating

```
submitSearch () {
      this.$router.push({
        name: 'search',
        params: { keyword: this.keyword }
      })
    }

```
For live example you can see this on my site

> https://www.umardraz.com/login
> username = admin
> password = Passw0rd
> 

You can find the search box right sider the header.

**Comment by PeachScript** [comment]
`vue-router` will reuse component if previous route and current route base on the same component, so the `infinite-loading` component is still in complete, you can reset it in the `beforeRouteUpdate ` guard.

**Comment by umardraz** [comment]
Thanks for your reply,

If you give a little example that will help me, specially how to reset infinite-loading with beforeRouteUpdate

**Comment by PeachScript** [comment]
See the `$infiniteLoading:reset` event in [docs](https://peachscript.github.io/vue-infinite-loading/#!/events), send it like this:

```js
...
beforeRouteUpdate(_to, _from, next) {
  this.$refs.infiniteLoading.$emit('$InfiniteLoading:reset');
  next();
}
...
```

**Comment by umardraz** [comment]
Hi

I have tried this one 

https://peachscript.github.io/vue-infinite-loading/#!/getting-started/with-filter

and here is my code

```
    changeFilter() {
      this.users = []
      this.$nextTick(() => {
        this.$refs.infiniteLoading.$emit('$InfiniteLoading:reset')
      })
    }

```
And here is beforeRouteUpdate

 ```
 beforeRouteUpdate (to, from, next) {
    this.changeFilter()
  }
```

Now I am getting this error 

TypeError: Cannot read property '$emit' of undefined

**Comment by PeachScript** [comment]
Did you forgot to set `ref` attribute to `infinite-loading` element?

**Comment by PeachScript** [comment]
To checkout official docs: [ref](https://vuejs.org/v2/api/#ref).

**Comment by umardraz** [comment]
Perfect great :)

Worked
