### ISSUE TITLE
"infinite" not called on Firefox

### ISSUE THREAD

**Issue by chypriote** [PeachScript/vue-infinite-loading#147]
### Version
2.3.1

### Vue.js version
2.5.16

### What is expected?
When the page loads, the function associated to the infinite field should be called.

### What is actually happening?
Tested on Chrome, IE11 and Edge, it works without any problem. On Firefox though, the function is never called.
However, if my reduce the height of the window until a scrollbar appears, 'infinite' is triggered and the data loads how it should.

### How to reproduce this problem?
I'm using something very basic
```
		<infinite-loading @infinite="getData">
			<div slot="no-results">No results</div>
			<div slot="no-more">No more</div>
			<div slot="spinner"><i class="loader"></i></div>
		</infinite-loading>
```
You can check it on [this page](http://chypriote.com/classements)

**Comment by PeachScript** [comment]
@chypriote I've been reproduced the problem on your website, but I cannot debug it with the minified code, so could you create a minimal viable program on some live example website?
