### ISSUE TITLE
Trigger infiniteLoading on custom event

### ISSUE THREAD

**Issue by umervservices** [PeachScript/vue-infinite-loading#148]
### Version
2.3.1

### Vue.js version
2.5.13

### What is expected?
reload the list on promise resolve for deleting an item I've tried 
```
    this.$nextTick(() => {
        this.$refs.infiniteLoading.attemptLoad();
    });
```
 but no hope

### What is actually happening?
no triggering the 
infiniteHandler($state)

**Comment by umervservices** [comment]
Showing you the code

Template
```

<template>
<div v-for="(commentReply, key) in Data" class="alert alert-dark fade show" v-if="isTriggerFirstLoad">
  <div>{{commentReply.comment}}</div>
  <!-- Delete Trigger -->
  <!-- I want to reload the list when destroy method called -->
  <button data-dismiss="alert" type="button" class="close" aria-label="Close" @click="destroy(var, var2)">
              <span aria-hidden="true"><i class="fa fa-times"></i></span>
            </button>
  </span>
</div>
<button class="btn-load-more" @click="isTriggerFirstLoad = true" v-if="!isTriggerFirstLoad">View Replies</button>
<infinite-loading @infinite="infiniteHandlerReplies" ref="infiniteLoading" v-else>
  <!-- v-else -->
  <!-- Check if Events are Available -->
  <div v-if="commentReplies.length === 0" class="article-preview" slot="no-more">
    {{ notFound }}
  </div>

  <!-- Check if Events Loading Ended -->
  <span v-else slot="no-more">
      {{ endLoading }}
    </span>
</infinite-loading>
</template>
```


Methods

```
manualLoad() {
      this.$nextTick(() => {
        this.$refs.infiniteLoading.attemptLoad();
      });
    },
    destroy(commentId, commentReplyId) {
      this.$store.dispatch(COMMENT_REPLY_DESTROY, {
          var,
          var2
        })
        .then(() => {
          this.manualLoad()
        })
    },
```

**Comment by PeachScript** [comment]
@umervservices sorry I missed your comment, is the problem still exists?

**Comment by lucassonsinlima** [comment]
@PeachScript hi :), I'm trying to reuse infinite loading on the same page to manually load children components into the parent component that already have been loaded with the lib, like a 'load more' function. Is there a way to run infinite loading at a custom event? a click for example. I'm trying and I can't find a beautiful way to do this. I found this fiddle https://jsfiddle.net/21g39g3p/ but I can't reproduce this cenario into my components. Thanks for this wonderful lib, I know load more is out of the infinite loading concept that the lib is focused but I'm trying to find a clean way.

**Comment by PeachScript** [comment]
@lucassonsinlima there has [a demo](https://peachscript.github.io/vue-infinite-loading/old/#!/getting-started/trigger-manually) in the old version of the documentation, hope it can help you.

**Comment by lucassonsinlima** [comment]
@PeachScript great! I made some changes at the logic just to cover my cenario and worked perfectly! 

Thanksss a lot !  :))

**Comment by PeachScript** [comment]
@lucassonsinlima you're welcome :D

**Comment by seunafara** [comment]
Hi great library. I tried to call this method:

`manualLoad() {
      this.$nextTick(() => {
        this.$refs.infiniteLoading.attemptLoad();
      });
    },`

but get this error:

`TypeError: Cannot read property 'attemptLoad' of undefined`

How do I fix this please?

**Comment by Kealtie** [comment]
> Hi great library. I tried to call this method:
> 
> `manualLoad() { this.$nextTick(() => { this.$refs.infiniteLoading.attemptLoad(); }); },`
> 
> but get this error:
> 
> `TypeError: Cannot read property 'attemptLoad' of undefined`
> 
> How do I fix this please?

You need the ref to the element in HTML , like this `<infinite-loading @infinite="infiniteHandler" ref="infiniteLoading">`
