### ISSUE TITLE
Error with webpack/buble @next

### ISSUE THREAD

**Issue by Cabbaggio** [PeachScript/vue-infinite-loading#15]
I call `import test from 'vue-infinite-loading'` in my js-file. Now i get an error message from webpack/buble: `Module build failed: SyntaxError: 'with' in strict mode (1:9374)`

I use the @next version with vue2.0

**Comment by Cabbaggio** [comment]
I got it. I just have to exclude the node_modules in my buble-loader: `exclude: /(node_modules)/`

**Comment by vlahde** [comment]
> I got it. I just have to exclude the node_modules in my buble-loader: exclude: /(node_modules)/

Exactly how do you do this?

**Comment by Cabbaggio** [comment]
Do you use Laravel? 
Than use this package 'https://github.com/vuejs/laravel-elixir-vue-2' or add the following code to your gulp file 
```
elixir.ready(function() {
    Elixir.webpack.config.module.loaders = [
        { test: /\.vue$/, loader: 'vue' },
        { test: /\.js$/, exclude: /(node_modules)/, loader: 'babel' }
    ]
});
```

**Comment by vlahde** [comment]
Thanks for the help. I am using Laravel and installed elixir-vue-2. I have added your code to gulpfile and get now this error: "{ [Error: Entry module not found: Error: Can't resolve 'babel' in 'c:\xampp\htdocs\b2c2'
resolve 'babel' in 'c:\xampp\htdocs\b2c2'"

here is my gulpfile;
``const elixir = require('laravel-elixir');

require('laravel-elixir-vue-2');

elixir.ready(function() {
    Elixir.webpack.config.module.loaders = [
        { test: /\.vue$/, loader: 'vue' },
        { test: /\.js$/, exclude: /(node_modules)/, loader: 'babel' }
    ]
});
 
elixir(mix => {
    mix.sass(['app.scss', 'chat.scss'])
        .webpack('app.js')
        .webpack('chat.js');
});

**Comment by Cabbaggio** [comment]
ah sry Laravel elixir use buble instead of babel.

I think you dont need to add the elixir ready part. It is part of the `laravel-elixir-vue-2` package
try this:
```
const elixir = require('laravel-elixir');
require('laravel-elixir-vue-2');

elixir(mix => {
  mix
   .sass(['app.scss', 'chat.scss'])
   .webpack('app.js')
   .webpack('chat.js');
});
```

if that not work try this:

```
const elixir = require('laravel-elixir');
require('laravel-elixir-vue-2');

elixir.ready(function() {
  Elixir.webpack.config.module.loaders = [
    { test: /.vue$/, loader: 'vue' },
    { test: /.js$/, exclude: /(node_modules)/, loader: 'buble' }
  ]
});

elixir(mix => {
  mix
    .sass(['app.scss', 'chat.scss'])
    .webpack('app.js')
    .webpack('chat.js');
});
```

**Comment by vlahde** [comment]
When trying to use buble I get this error 
` Entry module not found: SyntaxError: c:\xampp\htdocs\b2c2\node_modules\buble-loader\package.json (directory description file): SyntaxError: Unexpected token } in JSON at position 2559]`

**Comment by vlahde** [comment]
I get the error now even with my previous configuration!

**Comment by vlahde** [comment]
Okay. I got rid of all errors after destroying the node_modules folder and reinstalling it with npm install. Now I just have to figure out how to use infinte loading within my app :) thanks
