### ISSUE TITLE
Infinite loading not following window scroll.

### ISSUE THREAD

**Issue by kont-wayfinder** [PeachScript/vue-infinite-loading#151]
### Version
2.2.3

### Vue.js version
2.5.2

### What is expected?
Users scrolls down and content gets loaded

### What is actually happening?
Users have to scroll within an "inner div" to trigger infinite loading

### How to reproduce this problem?
Visit the below site on mobile:
https://kontinentalist.com/blog
Check it out in the "Latest Stories" section

**Comment by PeachScript** [comment]
Sorry for late, I cannot reproduce it, did you fixed it now?

**Comment by Mikkou** [comment]
Hi
I have some problem

url http://test.narod.io/buy-apartment
template http://joxi.ru/V2VbQBEcxLpEx2
js http://joxi.ru/D2PzbDGUp4Qjkr

you know how fix?

**Comment by Mikkou** [comment]
http://joxi.ru/RmzEpqNH0lXVpr
not helped 
i have infinity cycle

**Comment by PeachScript** [comment]
@Mikkou did you forgot to add `infinite-wrapper` attribute on the real scroll parent? In your case, it is the body element.
