### ISSUE TITLE
Version info in the dist/.js file

### ISSUE THREAD

**Issue by zapping** [PeachScript/vue-infinite-loading#154]
If you could include the version no in the dist/.js file then it will be helpful. Currently there is no way of knowing which version is currently being used in the project. If you could add something like this then it will be helpful.

![versioninfo](https://user-images.githubusercontent.com/4123026/41098206-1cba1070-6a4a-11e8-8bcd-e51b991cea1a.PNG)

Cheers

**Comment by PeachScript** [comment]
Good idea, I will add it in the next version, thanks!

**Comment by PeachScript** [comment]
Already added it in the [`v2.3.2`](https://github.com/PeachScript/vue-infinite-loading/releases/tag/v2.3.2).
