### ISSUE TITLE
is there a demo of using vue-infinite-loading in element-ui?

### ISSUE THREAD

**Issue by zzzgit** [PeachScript/vue-infinite-loading#158]
is there a demo of using vue-infinite-loading in element-ui?
especially in el-table

**Comment by PeachScript** [comment]
Sorry for late, it will be added recently in the new version of document.

**Comment by PeachScript** [comment]
Hi @zzzgit , there has a demo of using this plugin with Element UI in the [new docs](https://peachscript.github.io/vue-infinite-loading/guide/use-with-el-table.html), you can check out it now.

Please comment here if you find any problem.
