### ISSUE TITLE
[Feature] Pass Message To State Changer's complete() Function

### ISSUE THREAD

**Issue by MannikJ** [PeachScript/vue-infinite-loading#159]
### Version
2.3.1

### Vue.js version
2.6.16

### What is expected?
I would like to be able to pass a message to the state changer's `complete()` function. I think it is generally a good idea to be able to customize the configuration temporarily via the state functions as a lightweight alternative to writing slots. 
In my case I would for example catch an error an then call `$state.complete("Network issues. Fetch failed")` or something like that.

**Comment by PeachScript** [comment]
Sounds interesting, I will consider this feature, thanks!

**Comment by PeachScript** [comment]
Hi @MannikJ , the new version v2.4.0 has been released, contains a new slot named error to solve your problem, you can check out it in the [new docs](https://peachscript.github.io/vue-infinite-loading/guide/configure-load-msg.html) now.

Please comment here if you find any question :)
