### ISSUE TITLE
升级到1.1.1版本，vue-infinite-loading报错

### ISSUE THREAD

**Issue by whq731** [PeachScript/vue-infinite-loading#16]
报错信息如下
vue-infinite-loading.js:1
Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.e @ vue-infinite-loading.js:1(anonymous function) @ vue-infinite-loading.js:1

**Comment by PeachScript** [comment]
也许是程序出现了 bug，但我现在不方便验证问题是否存在，十分抱歉。

如果影响到你的使用，请先限制插件版本为 1.1.0，我会在国庆后修复/排除此问题，到时候在此条 issue 下面回复结果。

**Comment by whq731** [comment]
嗯 现在已经锁定版本使用

**Comment by PeachScript** [comment]
经过验证发现这是一个自动化测试没有测试出来的问题，是由于我在 `v1.1.0` 的基础上优化代码时出现的程序逻辑错误，我已在 [v1.1.2](https://github.com/PeachScript/vue-infinite-loading/releases/tag/v1.1.2) 中修复此问题，并在 `npm` 中 `deprecate` 了 `v1.1.1` 版本。

此前外出没有电脑拖到现在才解决，再次抱歉。非常感谢你的反馈 : )
