### ISSUE TITLE
Error when updating from version 1.1.0 to 1.1.1

### ISSUE THREAD

**Issue by hessnd** [PeachScript/vue-infinite-loading#17]
I had to reinstall my node modules directory and after downloading the new version I would get this console error: 

`Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

If I revert back to version 1.1.0 I have no error.

**Comment by whq731** [comment]
same as https://github.com/PeachScript/vue-infinite-loading/issues/16

**Comment by PeachScript** [comment]
@hessnd I has been fixed this problem in [v1.1.2](https://github.com/PeachScript/vue-infinite-loading/releases/tag/v1.1.2), and I deprecated `v1.1.1` in `npm`, please try to use the `v1.1.2` to replace it.
