### ISSUE TITLE
why  I get multiple request?

### ISSUE THREAD

**Issue by YiBanCangBai** [PeachScript/vue-infinite-loading#172]
<template>
</template>
<script>
import api from '@/service/api/product'
import '@/assets/dialog/fm.dialog.min.css'
import { Dlg } from '@/assets/dialog/fm.dialog.min.js'
import InfiniteLoading from 'vue-infinite-loading'

let _busy = 0

export default {
  name: 'productList',
  components: {
    InfiniteLoading
  },
  // props: ['productList'],
  data () {
    return {
      productList: [],
      productPage: 1
    }
  },
  mounted () {
    // this.init()
  },
  methods: {
    // async init () {
    //   this.getProductListFn()
    // },
    async getProductListFn ($state) {
      _busy = 1
      const res = await api.getProductList({page: this.productPage, pageCount: 10})
      const { data } = res
      if (!data || Object.keys(data).length === 0) {
        Dlg.msg({
          content: '数据异常',
          msgType: 'error'
        })
        return false
      }
      const {groupGoodsView} = data
      if (groupGoodsView.length) {
        this.productPage++
        this.productList = this.productList.concat(groupGoodsView)
        $state && $state.loaded()
      } else {
        $state && $state.complete()
      }
      _busy = 0
    },
    infiniteHandler ($state) {
      console.log(_busy)
      if (_busy === 0) {
        console.log('come in')
        this.getProductListFn($state)
      }
    }
  }
}
</script>

result:
console 'come in' twice and send two net request

**Comment by PeachScript** [comment]
Did the first screen be filled up after the first request? If not this plugin will attempt infinite event until the first screen is filled.

**Comment by YiBanCangBai** [comment]
Thanks! @PeachScript

**Comment by PeachScript** [comment]
@YiBanCangBai you are welcome :)
