### ISSUE TITLE
Middle buttons scroll in Chorme does not trigger infinite event 

### ISSUE THREAD

**Issue by phoenixcz** [PeachScript/vue-infinite-loading#174]
Hi,
when using the middle button scroll in Chrome or just scroll really quickly, the infinite event is not triggered.

In attached gif - first normal scroll is used (works fine), then middle button scroll is used (doesn't work), then when I scroll up a bit, infinite event is triggered.

![infiniteloading](https://user-images.githubusercontent.com/18397435/44087536-71883f7c-9fc0-11e8-8a7d-aa51f26e1e85.gif)

Jsfiddle to reproduce: https://jsfiddle.net/phoenixcz/81q6bmLh/35/

Thanks for any tips on how to make this work.

### Version
Vue-infinite-loading: 2.3.2
Chrome: 68.0.3440.106

**Comment by PeachScript** [comment]
@phoenixcz it looks like the throttle feature does not work correctly in the `v2.3.3`, you can try the latest version `v2.3.3`, if this problem still exists, please comment here, thanks!

**Comment by phoenixcz** [comment]
It seems issue is resolved with latest update. Thanks.
