### ISSUE TITLE
发两次请求

### ISSUE THREAD

**Issue by xihadandan** [PeachScript/vue-infinite-loading#176]
外部容器已经填充满了为何还发两次请求

**Comment by xihadandan** [comment]
以下是具体代码，console.log($state)打印为空
<infinite-loading @infinite="infiniteHandler"></infinite-loading>
 infiniteHandler ($state) {
      console.log($state)
    },

**Comment by goSunadeod** [comment]
解决了吗，是什么原因呢

**Comment by xihadandan** [comment]
解决了，是内容没填满容器

**Comment by xihadandan** [comment]
解决了，是内容没填满容器

**Comment by xihadandan** [comment]
解决了，是内容没填满容器

**Comment by goSunadeod** [comment]
我这边遇到 如果滚动条往下滚动一点时，reset就会调两次请求，和您的类似吗

**Comment by xihadandan** [comment]
你可以把代码贴出来看看

**Comment by goSunadeod** [comment]
<el-table-column
            prop="projectStageDesc"
            label="阶段"
            align="center"
            :show-overflow-tooltip="true"
            min-width="80">
          </el-table-column>
          <template slot="append">
            <infinite-loading ref="Infinite" @infinite="onInfinite" spinner="circles">
          <span slot="no-more">
          —————————————————————————— 加载完成 ————————————————————————————
          </span>
              <span slot="no-results">暂无数据</span>
            </infinite-loading>
          </template>
        </el-table>
主要是配合el-table使用， 我给table设置了最大高度，数据量多的话就会出现滚动条，如果我没有滚动，直接触发this.$refs.Infinite.$emit('$InfiniteLoading:reset') 此请求只会发一次，但是如果稍微滚动了，再reset时，就会触发两次请求。

**Comment by goSunadeod** [comment]
<el-table-column
            prop="projectStageDesc"
            label="阶段"
            align="center"
            :show-overflow-tooltip="true"
            min-width="80">
          </el-table-column>
          <template slot="append">
            <infinite-loading ref="Infinite" @infinite="onInfinite" spinner="circles">
          <span slot="no-more">
          —————————————————————————— 加载完成 ————————————————————————————
          </span>
              <span slot="no-results">暂无数据</span>
            </infinite-loading>
          </template>
        </el-table>

**Comment by goSunadeod** [comment]
嗯，没办法 页面需求，我再想想试一试，非常感谢
