### ISSUE TITLE
Better TypeScript handling

### ISSUE THREAD

**Issue by kartsims** [PeachScript/vue-infinite-loading#177]
Trying to use your lib with TypeScript here and can't import the component properly.

As per [these recommendations](https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html), one should export either a structured object or have a `default` export.

I personally prefer the `default` path since it would allow to use the same syntax for TS as for JS (so no need to add anything in the README)

Here is the diff that did the trick for me (`types/index.d.ts`) :

```
50c50
< export default InfiniteLoading;
---
> export = InfiniteLoading;
```

**Comment by PeachScript** [comment]
Hi @kartsims , it is better, thanks for your PR!

**Comment by PeachScript** [comment]
@kartsims hello, I have been released a new version `v2.3.4` contains this change, but it cannot works correctly when import declaration from namespace:

```js
import InfiniteLoading, { StateChanger } from 'vue-infinite-loading';
```

But it works well when using `export = InfiniteLoading;`, do you know the real reason?

**Comment by kartsims** [comment]
Have you tried :

```
import * as InfiniteLoading, { StateChanger } from 'vue-infinite-loading';
```

**Comment by kartsims** [comment]
Or as [this SO thread](https://stackoverflow.com/a/33611943/3169999) implies, you might need to write :

```
import { default as InfiniteLoading, StateChanger } from 'vue-infinite-loading';
```

Not very convenient tho

**Comment by PeachScript** [comment]
I tried just now, but TypeScript throw an error like this:

```
Module '"/path/to/project/node_modules/vue-infinite-loading/types/index"' has no exported member 'StateChanger'.
```

Did you see it when using `v2.3.4`?
