### ISSUE TITLE
"retry" action when loading data failed?

### ISSUE THREAD

**Issue by LouWii** [PeachScript/vue-infinite-loading#181]
Hi there,

Super nice plugin, I was able to get it working really quickly.

I'm fetching data via ajax when `infiniteHandler` is called. I was wondering how I should handle the case where the loading fails. I was thinking of displaying a message with a "Retry" button that would trigger `infiniteHandler` again to try to load the data again.

It would be a nice example to include in the documentation 😊

**Comment by PeachScript** [comment]
Glad you like it, and thanks for your suggestion! I think add a new API like `loaded` or `complete` to support it would be better, perhaps it will be added in the next minor version.

For now, you could display a retry button manually, bind a `click` event to trigger the `attempLoad` method from the `InfiniteLoading` instance, but it sounds a little complex 😔

**Comment by PeachScript** [comment]
Hi @LouWii , the new version `v2.4.0` has been released, contains a new slot named `error` to solve your problem, you can check out it in the [new docs](https://peachscript.github.io/vue-infinite-loading/guide/configure-load-msg.html) now.

Please comment here if you find any question :)
