### ISSUE TITLE
element-ui table 下拉加载 ，重新reset 如果出现滚动条就会触发两次

### ISSUE THREAD

**Issue by goSunadeod** [PeachScript/vue-infinite-loading#183]
### Version
2.3.3
### Vue.js version  
2.5.3
### ElementUI version
2.2.2
### What is Expected?
    <el-table-column
            prop="projectStageDesc"
            label="阶段"
            align="center"
            :show-overflow-tooltip="true"
            min-width="80">
          </el-table-column>
          <div slot="append">
            <infinite-loading ref="Infinite" @infinite="onInfinite" spinner="circles">
          <span slot="no-more">
          —————————————————————————— 加载完成 ————————————————————————————
          </span>
              <span slot="no-results">暂无数据</span>
            </infinite-loading>
          </div>
        </el-table>
### What is actually happening?
刷新是没问题的，但是触发$InfiniteLoading:reset的时候，如果table内部先出现滚动条，再reset的时候就会触发两次请求，如果我滚动条居于顶点时，则reset只会触发一次请求。请教是什么原因呢？

**Comment by goSunadeod** [comment]
forceUseInfiniteWrapper 设置为true 即可，但是文档也没更新啊，源码里倒是有说明

**Comment by PeachScript** [comment]
文档中确实缺少这个说明，我会在下一版文档中更新
