### ISSUE TITLE
$InfiniteLoading:reset and scroll event may trigger concurrent attemptLoad and force application to send two same ajax requests.

### ISSUE THREAD

**Issue by DustinPT** [PeachScript/vue-infinite-loading#189]
### Version
2.3.5
### Vue.js version
2.5.16
### Reproduction Link

https://codepen.io/dustinpt/pen/bmxMVm

### snapshots
Two request snapshot from chrome dev tool:

First request:
<img width="317" alt="emit_reset" src="https://user-images.githubusercontent.com/6522392/47138078-06ead180-d2eb-11e8-82d5-8cc732d91485.png">

Second request:
<img width="319" alt="scroll_triggered" src="https://user-images.githubusercontent.com/6522392/47138085-0b16ef00-d2eb-11e8-95f5-29538a66a0de.png">

**Comment by PeachScript** [comment]
Could you provide a reproduce link?

**Comment by DustinPT** [comment]
> Could you provide a reproduce link?

I have create one in codepen: https://codepen.io/dustinpt/pen/bmxMVm

**Comment by DustinPT** [comment]
Hello @PeachScript , Our problem scene is different from what you said.
We have a search page. Sometimes, when the user clicks the search button, two pages of the same data appear on the page.
After debugging, we found that after clicking the search button, the page issued two identical ajax requests at the same time.
Our page processing code is very simple. After clicking the search button, the data list is cleared and a reset event is issued to vue-infinite-loading.
Later we looked at the code of vue-infinite-loading, the problem should be like this.
After clearing the data list, the scroll event may be issued when the page is re-rendered. When the vue-infinite-loading component processes both the scroll event and the reset event, two data requests may be issued at the same timing.

time | reset event thread  | scroll event thread
---- | ------------ | -------------
1| event received| 
2| [InfiniteLoading.vue:192](https://github.com/DustinPT/vue-infinite-loading/blob/e613ddef5b36b91f6561ad4f7f7351862737a34d/src/components/InfiniteLoading.vue#L192) | 
3| | event received
4| | [InfiniteLoading.vue:144](https://github.com/DustinPT/vue-infinite-loading/blob/e613ddef5b36b91f6561ad4f7f7351862737a34d/src/components/InfiniteLoading.vue#L144)
5| [InfiniteLoading.vue:150](https://github.com/DustinPT/vue-infinite-loading/blob/e613ddef5b36b91f6561ad4f7f7351862737a34d/src/components/InfiniteLoading.vue#L150) |
6| [InfiniteLoading.vue:251](https://github.com/DustinPT/vue-infinite-loading/blob/e613ddef5b36b91f6561ad4f7f7351862737a34d/src/components/InfiniteLoading.vue#L251) |
7| | [InfiniteLoading.vue:145](https://github.com/DustinPT/vue-infinite-loading/blob/e613ddef5b36b91f6561ad4f7f7351862737a34d/src/components/InfiniteLoading.vue#L145)
8| | [InfiniteLoading.vue:251](https://github.com/DustinPT/vue-infinite-loading/blob/e613ddef5b36b91f6561ad4f7f7351862737a34d/src/components/InfiniteLoading.vue#L251)

**Comment by PeachScript** [comment]
Hi @DustinPT , thanks for your detailed explanation! I've reproduced this problem on my computer, and fixed it with the [`v2.4.1`](https://github.com/PeachScript/vue-infinite-loading/releases/tag/v2.4.1), you can try it now, please comment here if this problem still exists.

Best Regards.

**Comment by lucassonsinlima** [comment]
Hi @PeachScript, I'm facing the same problem, 2 same requests at the same page, on first load of infinite-loading, I already updated to v2.4.1.

First load:
![same_request](https://user-images.githubusercontent.com/25435624/48517771-8b7b3200-e84e-11e8-80dc-883df1b3b5d8.png)

At this component I'm using the default structure:
```
infiniteHandler($state) {
  axios.get(api, {
    headers: {
      'Accept' : 'application/json'
    },
    params: {
      page: this.page,
    },
  }).then(({ data }) => {
  if (data.length > 0) {
      this.page += 1;
      this.list.push(...data);
      $state.loaded();
    } else {
      $state.complete();
    }
  })
}
```
I can give more details if you need :)

**Comment by PeachScript** [comment]
@lucassonsinlima is your problem caused by `$state.reset()`?

**Comment by lucassonsinlima** [comment]
> @lucassonsinlima is your problem caused by `$state.reset()`?

Noup, I thought in opening another issue to my problem but this is quite similar due to the double requests at loading. Do you prefer that I open another one with my infos? Thanks :)

**Comment by PeachScript** [comment]
@lucassonsinlima that's great! Don't forget to provide a reproduce link in the new issue :P

**Comment by denglai** [comment]
Two tab tags, one use vue-infinite-loading, the other isn‘t  use。the component of  not using vue-infinite-loading plugin  slides to the bottom, then switch tab to the component of using vue-infinite-loading, there will be double request at loading with the same data

**Comment by PeachScript** [comment]
@denglai please provide a reproduce link, thanks.

**Comment by cwilby** [comment]
Just dropping a note here, one workaround I have for this is to only add new elements by changing `this.tasks.push(...data)` to:

```js
this.tasks = [
  ...this.tasks,
  ...data.filter(task => this.tasks.all(t => t.id !== task.id))
];
```
