### ISSUE TITLE
Failed to mount component: template or render function not defined.  (found in component <infinite-loading>)

### ISSUE THREAD

**Issue by tzookb** [PeachScript/vue-infinite-loading#19]
any ideas why is that error?

```
 Failed to mount component: template or render function not defined. 
```

(found in component <infinite-loading>)

I use these versions:

```
"vue": "^2.0.2",
"vue-infinite-loading": "^2.0.0-rc.1"
```

**Comment by PeachScript** [comment]
This is the one of `Vue.js` changes, maybe this guide can solve your problem: [Standalone-vs-Runtime-only-Build](https://vuejs.org/guide/installation.html#Standalone-vs-Runtime-only-Build).

**Comment by tzookb** [comment]
@PeachScript any ideas how to make it work with alisify for browserify?
still gives me same error :/

**Comment by PeachScript** [comment]
@tzookb Did you used the `Runtime-only` version of `Vue.js 2.0`?

**Comment by tzookb** [comment]
yes I read it, but not sure if i understood how to do it.

do you use alisify? with browserify or webpack?

**Comment by PeachScript** [comment]
No I don't, but I think it maybe like this:

webpack.config.js
```js
...
if (process.env.NODE_ENV === 'development') {
  module.exports.resolve.alias = {
    'vue$': 'vue/dist/vue.js'
  };
}
...
```

main.js
```js
import Vue from 'vue';
...

```

The alias will replace `Vue` to `Standalone` version when the environment is development.

**Comment by PeachScript** [comment]
Hello @tzookb , is your problem solved?

**Comment by tzookb** [comment]
had to much problems, so I stuck with vue 1 for now :/

**Comment by PeachScript** [comment]
Well, hope you use smoothly :P.

I will close this issue now, you can reopen it if you need in the future.

**Comment by stephanmax** [comment]
I am still getting this error, trying both standalone and runtime-only version. Any hint what I might be missing?

**Comment by PeachScript** [comment]
@stephanmax Could you paste your build configuration file and component file on the [JSFiddle](https://jsfiddle.net/)?
