### ISSUE TITLE
Best way to use plugin with Vuex

### ISSUE THREAD

**Issue by qWici** [PeachScript/vue-infinite-loading#190]
Can someone tell me what are the best way to uses of the plugin if I have all the data into Vuex state and this data mutate. Use global events?

**Comment by PeachScript** [comment]
I don't understand, you already have all data, why need to load more data through scroll?

**Comment by foxmask** [comment]
how to get the data with the plugin from vuex ? if my back end return 20 items per page, where could we use/set infiniteLoop ? in getter ? api ? action ?
I can't use infiniteLoop in the methods() on the component to make the (back end) API call as this one is already done in api.js of the module.
Any tips ?

**Comment by qWici** [comment]
@PeachScript I mean my data stored into Vuex state.

**Comment by qWici** [comment]
@foxmask Just use [vuex-rest-api](https://github.com/christianmalek/vuex-rest-api)

**Comment by foxmask** [comment]
@qwici thanks but I don't need it. I already be able to get the data. I just need to retrieve them page by page. So i'm looking for a way to do it with your project and vuex, if possible. 
Thanks

**Comment by oroalej** [comment]
Hi @qWici 

Did you encounter an error like this `$attrs is readonly` when using Vuex?
