### ISSUE TITLE
Infinite scroll does not stop loading. 

### ISSUE THREAD

**Issue by corbin88** [PeachScript/vue-infinite-loading#192]
### Version
vue-infinite-loading : 2.4.0
### Vue.js version
vue: 2.5.7
### Reproduction Link

I tried to reproduce the problem in a codepen, but it seems to work fine. I figured it had something to do with the overflow being set to auto, or not being able to work in a modal, but it seems to work just fine on the reproduction link.

https://codepen.io/Corbin/pen/jeQjvG?editors=1010

### My projects code

**Template**

```
<div class="single-conversation w-full h-full px-6 overflow-auto"><!-- End Scrollable content -->
    <infinite-loading direction="top" force-use-infinite-wrapper="true" @infinite="getOldMessages"></infinite-loading>
    <div v-for="message in messages" class="msgs flex flex-col items-center justify-between">
        <div class="p-4 border-b" v-if='message.sender.id == userId' :class="{me:message.name='Jim'}">
            <p>{{message.body}}</p>
        </div>
        <div class="p-4 border-b" v-else :class="{him:true}">
            <p>{{message.body}}</p>
        </div>
    </div>
</div><!-- End Scrollable content -->
```

**Component**
```
data: function() {
    return {
      messages: [],
      message: '',
      convoId: null,
      receiverUserAvatar: null,
      receiverUsername: null,
      page: 1,
    }
},

methods: {
    getOldMessages() {
        setTimeout(function() {
            axios({
                    method: 'get',
                    //This works by querying the receiving user id  (this.receiverId) 
                    //to see if there is a conversationBetween sender and the receiving user
                    url: '/conversations/' + this.receiverId + '?page=' + this.page,
                }).then(function(response) {
                    //Gets conversation id so sendMessage() 
                    //Can send to appropriate Conversation
                    this.convoId = response.data.conversation.id;

                    //Sets the modals header with receiving
                    //users avatar and username
                    this.setHeader(response.data.conversation.participants);

                    //Checks to see if there are any messages for infinite scroll
                    if (response.data.messages.data.length) {
                        //Puts indexed object items from reponse in an indexed array and reverese
                        //The order
                        const arr = [];

                        Reflect.ownKeys(response.data.messages.data).forEach((k) => {
                            arr[k] = response.data.messages.data[k];
                        });

                        this.messages = arr.reverse();
                        this.page += 1;
                        $state.loaded();
                    } else {
                        $state.complete();
                    }

                    //Scrolls to bottom of messenger
                    this.$nextTick(() => {
                        this.scrollToEnd();
                    });


                    //Connects to socket.io 
                    let socket = io(`http://localhost:3000`);
                    //Pushes new message to messages array.
                    socket.on('message', function(data) {

                        this.messages = this.objectPushToArray(data.message[0]);

                    }.bind(this));

                }.bind(this))
                .catch(function(error) {

                });
        }.bind(this))
    },
}
```
### What is actually happening?
A similar issue seems to be happening where the load doesn't stop[[issue 55]](https://github.com/PeachScript/vue-infinite-loading/issues/55), but the loads scroll wheel simply just keeps spinning above and doesn't seem to be loading any new content at all. 

![messenger-problem 2018-10-25 20_37_45](https://user-images.githubusercontent.com/24969455/47542489-a986ef80-d8ab-11e8-890b-062678653310.gif)

### What is Expected?

That infinite scroll loads messages then doesn't load anymore more messages until you scroll up.

**Comment by PeachScript** [comment]
Hi @corbin88 , this plugin will fire the `infinite` event again and again until the first screen be filled up, so in your case, you need to push enough data to fill up the first screen in the first load, then it should to work properly.

By the way, the `forceUseInfiniteWrapper` looks like unnecessary, and you can checkout the [official demo](https://peachscript.github.io/vue-infinite-loading/guide/top-dir-scroll.html), perhaps it can help you to solve this problem.

**Comment by corbin88** [comment]
@PeachScript , thanks. It looks like I missed passing the $state arg to getOldMessages. My next question is what would I do if there isn't enough posts to fill the entire page?

**Comment by corbin88** [comment]
@PeachScript, thanks. Turns out I forgot to add the `$state` param to `getOldMessages($state)` . 

Sorry for taking out an issue with the problem being on my end.
