### ISSUE TITLE
infinite-loading 组件没有触发 infinite 事件

### ISSUE THREAD

**Issue by shixy96** [PeachScript/vue-infinite-loading#195]
从一个 使用了infinite-loading组件的 keep-alive 的页面，$router.push 到一个新的使用 infinite-loading 组件的页面，infinite-loading 组件没有触发 infinite 事件

**Comment by PeachScript** [comment]
请阅读 [issue 指南](https://github.com/PeachScript/vue-infinite-loading/blob/master/.github/CONTRIBUTING.md#issue-reporting-guidelines) 并基于 [bug report 模板](https://github.com/PeachScript/vue-infinite-loading/issues/new?template=BUG_REPORT.md) 创建 issue。
