### ISSUE TITLE
router-link 进入<keep-alive>的组件，infinite-loading 的 $state.loaded=undefined

### ISSUE THREAD

**Issue by shixy96** [PeachScript/vue-infinite-loading#196]
## actually happen： 持续加载，console logs $state.loaded=undefined，最后 No more data :)

**Comment by PeachScript** [comment]
查看了一下你提供的重现链接，此问题是 `keep-alive` 使用方式错误造成的。`keep-alive` 仅能用于动态组件，[官方文档](https://cn.vuejs.org/v2/api/#keep-alive)；以及在配合 `vue-router` 使用时需要包裹在 `router-view` 外面，[官方文档](https://router.vuejs.org/zh/api/#router-view)。

使用 `unpkg` 引入组件时，默认是引入最新版，所以版本号与最新版的版本号一致即可；另外，编写 issue 时请保留模板中的标题，在标题下方进行描述。

此 issue 暂时关闭，如仍有问题请继续在此评论。
