### ISSUE TITLE
Add an infinite-loading tag in each tab 

### ISSUE THREAD

**Issue by astronati** [PeachScript/vue-infinite-loading#197]
### Steps to reproduce
I have two tabs that are displayed through `v-show`. Only one at once can be displayed. In each tab there is an `<infinite-loading />` tag that load two different lists.

### What is actually happening?
The hidden tab does not trigger any action even if opened later. So only the first tab correctly loads items and the second one does not do anything.

**Comment by oroalej** [comment]
@astronati Have you found a solution? I just encountered this problem today -_-
