### ISSUE TITLE
Add validator not to same page request

### ISSUE THREAD

**Issue by Akari1987** [PeachScript/vue-infinite-loading#198]
Hi thanks for great plugin! 
I have same page request issue when the response is only one and need to add some processes to rendering it. 
Duplicate request may be caused before rendering response.
So this issue may occur by browser processing power or network speed.
To avoid it, could you add request validator not to same page request.
Sorry for my wrong English.
Best regards.  

https://codepen.io/irakaarozo/pen/eQNvQX

**Comment by PeachScript** [comment]
Does it duplicate with #189 ?

**Comment by Akari1987** [comment]
Sorry for my misunderstood. It occurred by getting distance  process.  Duplicate request only occurred when scroll down  and click router-link (vue-router) and init infiniteHandler. On the top of page, it does't occurred. 
So adding forceUseInifiniteWrapper, everything works well!!
![image](https://user-images.githubusercontent.com/13121500/48062840-8858c400-e206-11e8-8151-63bcb5c7838a.png)

Thanks for useful props!!
