### ISSUE TITLE
onInfinite not called when already scrolled down

### ISSUE THREAD

**Issue by arjanwestdorp** [PeachScript/vue-infinite-loading#2]
It happens sometimes that the onInfinite is not called. I investigate and saw this was because the `currentDistance` is bigger then the `this.distance`. I think it would be nice to have a option to call the onInfinite without checking the distance in these two situations:

1. When calling reset. Imagine I have on the left of my screen some filters which can be applied to show a list on the right. When i'm scrolling on the right it will fill my infinite list. But then I change filters on the left. Because I didn't scroll all the way up my `currentDistance` is too high and the list will not be reloaded.

2. When initializing the control it is also better to call the onInfinite without checking the distance. Because you want the first items always be loaded.

The second thing happened to me when using the chrome developer tools and made it too high which gave a `currentDistance` bigger then 100.

What do you think about this? If you want I can create a fix for this.

**Comment by PeachScript** [comment]
Thanks for your issue :D.

The first situation is a important question actually, so this component provide a way to reset all status of itself in the previous version, you just need execute `this.$broadcast('$InfiniteLoading:reset')` after change filter on the left of your screen, the component will reset all status and checking distance at once, hope it can help you.

For the second situation, this component will check distance once automatically after initializing already, and I think use developer tools or other scene belong to special cases, but every component was born to solve universal problems, so we should not call the `onInfinite` if the distance is not expected.Maybe we really need call the `onInfinite` in some special scenes, but why not direct call `onInfinite` manually?

**Comment by PeachScript** [comment]
Sorry, maybe I made a mistake.

I was aware of you are the contributor who improve this component to `v0.3.1` just now. I thought your first situation can be resolved by your previous pull-request and you needn't created this issue a week ago. 

But I don't know whether I understand your meaning correctly now, maybe you can tell me the truth.

**Comment by arjanwestdorp** [comment]
I thought already something like that. No problem.
Let me try to explain it based on two situations:

1. Imagine we want to show a list of tasks. When I enter the page there are no tasks. So the tasks needs to be loaded, this will be done by the control in the ready method `setTimeout(this.scrollHandler, 1);`
In the scrollHandler it will only call the onInfinite when it's not already loading and when the distance check matches, that's normally oke.
But I had sometimes issues with the distance check. It seems this check is not always working properly. That's why is was thinking that it would be better to call the onInfinite anyway ignoring the distance check. When intializing the control you want to show always the first items right?

2. The same is when resetting the control. Imagine we have a list of tasks and already scrolled down a few times which works perfect. Then I change my filters. That will clear all the tasks in the list and need to reload the first x items. But again it will only reload when the distance check is fine. Sometimes the distance check is not working then and the items are not loaded. User needs to scroll one time down and loading will start, which is a bit strange. When resetting the component we want to go to the initial state, which means in my opinion load the first x items. So it would be nice that if will trigger the onInfinite without checking the distance.

Checking the isLoading needs to be always there in my opinion. But checking the distance needs only to be done when the event is triggered by the scroll event and not in these situations:
- `setTimeout(this.scrollHandler, 1);`
- `this.scrollHandler();`

I hope it's a bit more clear now what I meant. 

How I solved this for now is that I always call the onInfinite by myself when entering the page and when resetting the filters. The only thing is then that the loading message does not appear, so it would be nicer if the control could handle this.

**Comment by PeachScript** [comment]
So that's it, I think I understand your meaning, thanks for your interpretation.

Before solve the problem that the loading message does not appear, I want to know why the distance check is not always working properly, and what is the special scene, I think it's the source problem, how do you think?

**Comment by arjanwestdorp** [comment]
I checked why the distance check is not working properly. Imagine this situation:

On the right I have my tasks list with 10 items -> height 1300px
document.body.scrollHeight -> 550px

On the left I have my filters. For example a textbox where I can search based on a string. When I hit enter there it starts searching.

This is a part of the code which is executed at that moment:
`this.tasks = []
this.totalTasks = null
this.$broadcast('$InfiniteLoading:reset')`

But when checking the distance the innerHeight is 1300 and the scrollHeight is 550 so it will not pass the check. After I hit enter again (with a empty list because of the this.tasks=[]) it works.

So I think that it takes a little bit of time to remove the tasks from the screen and before they are removed the distance check is called. Does that make sense?

**Comment by PeachScript** [comment]
You're right, execute `this.tasks = []` will take effect after the next Dom update. And we can use `Vue.nextTick` or `this.$nextTick` to wait Vue to update the Dom, like the following code:

```javascript
this.tasks = [];
this.$nextTick(function () {
  this.$broadcast('$InfiniteLoading:reset');
});
```

I think the problem can be solved.

**Comment by arjanwestdorp** [comment]
Thank you very much. This works fine, I didn't know about that option.

**Comment by PeachScript** [comment]
You're welcome :)
