### ISSUE TITLE
Feature: Loading when scroll to top

### ISSUE THREAD

**Issue by Aron-YCS** [PeachScript/vue-infinite-loading#20]
Thanks for you library bringing convenience to my job. I encounter a situation that need support of loading from top of scroll element.As lack of feature in this library, I can only implement it by my own,really time wasting.
I think this is quite a useful and necessary functionality.I just hope this library can be better and add it. Thanks again for your effort.

**Comment by PeachScript** [comment]
Glad you like this plugin.

There has the seem issue #8 already. I thought a lot after that, but I cannot imagine any situation which need an infinite scroll up plugin, because of such the plugin more like pull-refresh plugin rather than infinite scroll plugin. Perhaps I missed some situations, what do you think about it?

**Comment by julianfox** [comment]
+1

About my situation, I have to load more pages of a book where the user can go directly to the page 10 (for example) in this case I have to load the page 11 if the user scroll down and the page 9 if the user scroll top...

Thanks for this component :-)

**Comment by PeachScript** [comment]
@julianfox Thanks for your comment, I understood your situation and it does exist, but in my mind, we need to pull down or pull up to load another page rather than scroll down or scroll up directly when using some apps, is that right?

**Comment by PeachScript** [comment]
I will close this issue until we found some situations that really needed the feature in this component, thanks everyone :D

**Comment by znck** [comment]
Scroll up infinitely is required in messenger/chat apps, where you scroll up to load old messages.

**Comment by PeachScript** [comment]
@znck well, I think you're right, the iMessage App of iOS is like that, it will load old messages automatically when I scroll up.

I will reopen this issue and add this feature in the todo list, thank you!

**Comment by vlahde** [comment]
Thanks for the great component! I am also desperately looking a way to reverse distance so that infinite-loading would be triggered if clients scroll is over a certain amount of pixels from the bottom or under the certain amount of pixels from the top. I am developing a chat application and old chat messages are loaded when user hits the top of the chat area. So there is a need for this feature :)

**Comment by charliewolf** [comment]
:+1: we could also use this feature!

**Comment by PeachScript** [comment]
Hello everyone, I released a new version `v1.3.0` to support two direction load feature, the document is bottom of [this page](https://peachscript.github.io/vue-infinite-loading/#!/properties), please try it with `npm`, if it's ok, I will add it to the `v2.0.0` version.

Sorry, this feature was late for too long, thank you a lot : )

**Comment by charliewolf** [comment]
@PeachScript Does that mean it's only compatible with Vue 1.0? How hard would it be to backport (well, forward-port, I guess) the changes?

**Comment by PeachScript** [comment]
@charliewolf Right, I plan to support `Vue.js2.0` after this feature being stable, and it's very simple, see [file changes](https://github.com/PeachScript/vue-infinite-loading/commit/bf23c434d3305089d117876562aad8d91b0e8dc8), if you need, I can add it to `v2.0.0` recently.

**Comment by charliewolf** [comment]
@PeachScript Got it--well, I can only speak for myself obviously, but the app I could test this with is using Vue2.

**Comment by PeachScript** [comment]
@charliewolf Hello, I've added this feature into the latest stable version `v2.0.0`, you can test it in your app now.

**Comment by vlahde** [comment]
Thank you so much for this new feature! Works like a charm!

**Comment by PeachScript** [comment]
@vlahde You're welcome : )
