### ISSUE TITLE
component <infinite-loading> @infinite not working

### ISSUE THREAD

**Issue by luis7fj** [PeachScript/vue-infinite-loading#200]
@infinite not working

**It does not work like this**
`<template>
    <div class="navbar-item has-dropdown">
        <div class="navbar-link is-arrowless">
            <i class="fas fa-lg fa-bell"></i>
            <span class="is-rounded badge-notification"></span>
        </div>
        <div id="moreDropdown" class="navbar-dropdown is-right" style="max-width: 320px;">
                <infinite-loading @infinite="infiniteHandler"></infinite-loading>
            <div class="navbar-item pt-0" style="width: 100vw;">
                Tus notificaciones
            </div>
            <hr class="dropdown-divider is-marginless">
                <template v-for="notificacion in notificaciones">
                    <a class="navbar-item is-block pr-15" href="#" style="white-space:initial !important;" >
                    <article class="media">
                        <figure class="media-left">
                            <p class="image is-48x48">
                                <img src="/static/img/notifications/task.png" style="max-height:none;">
                            </p>
                        </figure>
                        <div class="media-content">
                            <div class="content">
                                <p><small>
                                    <strong>Soporte de página.</strong> <small></small> <small class="is-pulled-right">31m</small><br>
                                    <span style="line-height:1.2em !important;" class="is-block">Respondimos a tu mensaje o reporte formulada... </span></small>
                                </p>
                            </div>
                        </div>
                    </article>
                    </a>
                    <hr class="dropdown-divider is-marginless">
                </template>
            <div class="navbar-item pb-0">
                <a href="#" class="has-text-dark"><small><span class="fa fa-arrow-right" aria-hidden="true"></span> &nbsp; Ver todas</small></a>
            </div>
        </div>
    </div>
</template>`

`<script>
    import axios from 'axios';
    export default {
        name: "notificacion",
        data () {
            return {
                notificaciones: [0, 2, 3, 4,5, 6],
                unread_count: 0,
                page: 1,
                lista: [],
            }
        },
        mounted() {
            Echo.channel('canalnuevo')
                .listen('.App\\Events\\Event', (e) => {
                    this.unread_count++;
                });
        },
        methods: {
            mensaje() {
                alert(1);
            },
            infiniteHandler($state) {
                alert('infinite scroll');
                const api = '//hn.algolia.com/api/v1/search_by_date?tags=story';
                axios.get(api, {
                    params: {
                        page: this.page,
                    },
                }).then(({ data }) => {
                    if (data.hits.length) {
                        this.page += 1;
                        this.list.push(...data.hits);
                        $state.loaded();
                    } else {
                        $state.complete();
                    }
                });
            },
        }
    }
</script>`
`<style lang="scss" scoped>
    .badge-notification {
        position: absolute;
        background: red;
        color: white;
        display: block;
        top: 17px;
        right: 12px;
        width: 9px;
        height: 10px;
        text-align: center;
        font-size: 10px;
        font-weight:bold;
    }
</style>`

**But if I put it this way it works, why?**

`<template>
    <div class="navbar-item has-dropdown">
        <infinite-loading @infinite="infiniteHandler"></infinite-loading>
        <div class="navbar-link is-arrowless">
            <i class="fas fa-lg fa-bell"></i>
            <span class="is-rounded badge-notification"></span>
        </div>
        <div id="moreDropdown" class="navbar-dropdown is-right" style="max-width: 320px;">
            <div class="navbar-item pt-0" style="width: 100vw;">
                Tus notificaciones
            </div>
            <hr class="dropdown-divider is-marginless">
                <template v-for="notificacion in notificaciones">
                    <a class="navbar-item is-block pr-15" href="#" style="white-space:initial !important;" >
                    <article class="media">
                        <figure class="media-left">
                            <p class="image is-48x48">
                                <img src="/static/img/notifications/task.png" style="max-height:none;">
                            </p>
                        </figure>
                        <div class="media-content">
                            <div class="content">
                                <p><small>
                                    <strong>Soporte de página.</strong> <small></small> <small class="is-pulled-right">31m</small><br>
                                    <span style="line-height:1.2em !important;" class="is-block">Respondimos a tu mensaje o reporte formulada... </span></small>
                                </p>
                            </div>
                        </div>
                    </article>
                    </a>
                    <hr class="dropdown-divider is-marginless">
                </template>
            <div class="navbar-item pb-0">
                <a href="#" class="has-text-dark"><small><span class="fa fa-arrow-right" aria-hidden="true"></span> &nbsp; Ver todas</small></a>
            </div>
        </div>
    </div>
</template>`
`<script>
    import axios from 'axios';
    export default {
        name: "notificacion",
        data () {
            return {
                notificaciones: [0, 2, 3, 4,5, 6],
                unread_count: 0,
                page: 1,
                lista: [],
            }
        },
        mounted() {
            Echo.channel('canalnuevo')
                .listen('.App\\Events\\Event', (e) => {
                    this.unread_count++;
                });
        },
        methods: {
            mensaje() {
                alert(1);
            },
            infiniteHandler($state) {
                alert('infinite scroll');
                const api = '//hn.algolia.com/api/v1/search_by_date?tags=story';
                axios.get(api, {
                    params: {
                        page: this.page,
                    },
                }).then(({ data }) => {
                    if (data.hits.length) {
                        this.page += 1;
                        this.list.push(...data.hits);
                        $state.loaded();
                    } else {
                        $state.complete();
                    }
                });
            },
        }
    }
</script>`
`<style lang="scss" scoped>
    .badge-notification {
        position: absolute;
        background: red;
        color: white;
        display: block;
        top: 17px;
        right: 12px;
        width: 9px;
        height: 10px;
        text-align: center;
        font-size: 10px;
        font-weight:bold;
    }
</style>`

**Comment by PeachScript** [comment]
Please read [issue reporting guidelines](https://github.com/PeachScript/vue-infinite-loading/blob/master/.github/CONTRIBUTING.md#issue-reporting-guidelines) first, and create issue base on the issue template.
