### ISSUE TITLE
我在一个table中写了top和bottom的无限加载，但是只能一个有效，而且如果我不手动控制滚动条会一直触发请求。

### ISSUE THREAD

**Issue by zhutongtian** [PeachScript/vue-infinite-loading#201]
![image](https://user-images.githubusercontent.com/33335983/48682986-dd70de80-ebe5-11e8-8f9a-6239b750a7c6.png)
![image](https://user-images.githubusercontent.com/33335983/48683008-fc6f7080-ebe5-11e8-8c73-d77e24e63580.png)
![image](https://user-images.githubusercontent.com/33335983/48683027-1f9a2000-ebe6-11e8-86e8-976a076196df.png)

**Comment by PeachScript** [comment]
创建 issue 前请先阅读 [Issue Reporting Guidelines](https://github.com/PeachScript/vue-infinite-loading/blob/master/.github/CONTRIBUTING.md#issue-reporting-guidelines)，并且按照默认 issue 模板编写 issue，不符合规范的 issue 将会被直接关闭。

**Comment by zhutongtian** [comment]
请问是否能够实现一个table中同时向上和向下的无限加载，我的页面数据有3500条左右，我每一次触发加载必须把之前的数据替换掉，否则向下加载多了页面会卡顿。我现在已经能实现单独的向上或者向下加载

**Comment by PeachScript** [comment]
可以实现，此组件不会对你要实现的功能做任何限制，向上加载的示例可查看[官方文档](https://peachscript.github.io/vue-infinite-loading/zh/guide/top-dir-scroll.html)；但你需要自行处理 ElementUI 表格组件中 [slot 的限制](http://element-cn.eleme.io/#/zh-CN/component/table#table-slot)，它只支持 append。

**Comment by zhutongtian** [comment]
> 可以实现，此组件不会对你要实现的功能做任何限制，向上加载的示例可查看[官方文档](https://peachscript.github.io/vue-infinite-loading/zh/guide/top-dir-scroll.html) ;但你需要自行处理ElementUI表格组件中[槽的限制](http://element-cn.eleme.io/#/zh-CN/component/table#table-slot)，它只支持追加。

好的，谢谢您的回答，这是我第一次在GitHub提问，望见谅

**Comment by PeachScript** [comment]
不客气，以后请先仔细阅读 Issue Reporting Guidelines，如果你要提问的项目中有的话。

GitHub 欢迎你 :)
