### ISSUE TITLE
two components rendered on same page

### ISSUE THREAD

**Issue by kaisanjay** [PeachScript/vue-infinite-loading#203]
not showing spinner for one component and its only happening in chrome.
if i am using vue infinite loading for two components on same page there will be a problem in one always

**Comment by PeachScript** [comment]
Please read [Issue Reporting Guidelines](https://github.com/PeachScript/vue-infinite-loading/blob/master/.github/CONTRIBUTING.md#issue-reporting-guidelines) before create issue, thanks!
