### ISSUE TITLE
Something seems to be not working with tabs

### ISSUE THREAD

**Issue by mdeprezzo** [PeachScript/vue-infinite-loading#205]
### Version
2.4.0
### Vue.js version
2.5.7
### Reproduction Link

I'm using a tabs component, and in one of them, i have the infinite loading component, with identifier, that i update when the filter has been submitted from the the last tab. But, something goes wrong, because the loading never start, so how can i fix this ?

### Steps to reproduce
Try to use a tabs and in one of them use infinite loading component, in the the others tabs try to use a filter form, and on submit the form

### What is Expected?
After update the params, infinite loading need to start

### What is actually happening?
Nothing happen

**Comment by PeachScript** [comment]
Have you tested it with the latest version `v2.4.3`?

**Comment by PeachScript** [comment]
And please provide a reproduce link if the problem still exists in the latest version, thanks!
