### ISSUE TITLE
Allow to reset after end of data(Element UI table + infinite loading)

### ISSUE THREAD

**Issue by mrquokka** [PeachScript/vue-infinite-loading#206]
If scroll down before raise loaded.completed() (end of data)
and override infiniteid, table objects (another data) - infinite loading not work. cannot find it in $refs.
Can someone help me, how i can call reset method (if it help to me)?

P.S. If someone create FAQ with parameters, methods and slots (such us Element UI) it may be helpful!

**Comment by gabdsh** [comment]
I have this problem too (((

**Comment by PeachScript** [comment]
Hi @mrquokka @gabdsh , could you provide a reproduce link?

**Comment by mrquokka** [comment]
> Hi @mrquokka @gabdsh , could you provide a reproduce link?

https://jsfiddle.net/ju1koha9/

**Comment by mrquokka** [comment]
> @mrquokka you can reset this component via [`identifier` property](https://peachscript.github.io/vue-infinite-loading/api/#identifier), like the [filter/tabs demo](https://peachscript.github.io/vue-infinite-loading/guide/use-with-filter-or-tabs.html) in docs.

That a magic, i tried do it on more complicated object and it's not work. Thanks.
May be someone need this example https://jsfiddle.net/o7ypaxsr/

**Comment by PeachScript** [comment]
You're welcome! This issue will be closed now, thanks for your updated example :D

**Comment by oroalej** [comment]
Not working. Done it in tabs.
