### ISSUE TITLE
Error on destroy

### ISSUE THREAD

**Issue by astr0junk** [PeachScript/vue-infinite-loading#208]
Looks like the order of actions on destroy component not correct
 
![image](https://user-images.githubusercontent.com/1489351/49588200-32974900-f977-11e8-9824-ef792ba83953.png)
![image](https://user-images.githubusercontent.com/1489351/49588640-50b17900-f978-11e8-9cf9-489a27a9b47c.png)

I had a two tabs with lists of items and infinity loading and I have error each time when I switch tabs (tab components has not keep-alive attribute and re-rendered each time)

**Comment by PeachScript** [comment]
It looks like a bug, I will fix it as soon as possible, thanks for your report!

**Comment by astr0junk** [comment]
@PeachScript I found solution (code is near)
code is buggy cause when i switch tabs (component :is="etc code for switch component) in some moment elm.parentNode is NULL (i think it's connect with VueJS renderer speciality) like it's not in real DOM already or something. Solution is return this.$el if (elm.parentNode === null)

`getScrollParent(elm = this.$el) {
      let result;

      if (typeof this.forceUseInfiniteWrapper === 'string') {
        result = elm.querySelector(this.forceUseInfiniteWrapper);
      }

      if (!result) {
        if (elm.tagName === 'BODY') {
          result = window;
        } else if (!this.forceUseInfiniteWrapper && ['scroll', 'auto'].indexOf(getComputedStyle(elm).overflowY) > -1) {
          result = elm;
        } else if (elm.hasAttribute('infinite-wrapper') || elm.hasAttribute('data-infinite-wrapper')) {
          result = elm;
        }
      }

     if (!result && elm.parentNode === null) {
        return this.$el
      }

      return result || this.getScrollParent(elm.parentNode);
    },`

**Comment by PeachScript** [comment]
@astr0junk sorry for late, I tried to reproduce this problem via `component` component but no luck. I think we cannot use a wrong scroll parent element instead of the error message, it will make developer strange, why this component was not working but no error, so we should to find the real reason that why the `parentNode` was null, could you provide a reproduce link?

**Comment by d4rkr3pt0r** [comment]
@astr0junk I had your problem also. The weird thing is that the problem caused suddenly without changing anything!! BTW your solution fixed mine too 👍  Thanks

**Comment by anat** [comment]
Hi, I encounter the exactly same error using Nuxt.js,

Do you know if the plugin works well with Nuxt ?
