### ISSUE TITLE
vue 单页应用 第一页数据触发两次？

### ISSUE THREAD

**Issue by Hopingocean** [PeachScript/vue-infinite-loading#213]
### Reproduction Link
$state.loaded();
if (this.page > totalPage) {
   $state.complete();
}

### What is actually happening?
页面加载时会触发两次第一页的数据请求

**Comment by PeachScript** [comment]
请提供重现链接和完整的重现步骤

**Comment by Hopingocean** [comment]
The problem is accidental.

**Comment by Hopingocean** [comment]
warn:如果哪位也出现类似的问题，请使用2.3.1版本，虽然没找到问题所在，但是问题是肯定存在的，是偶发的
