### ISSUE TITLE
 Error in nextTick: "TypeError: Cannot read property '$emit' of undefined" 

### ISSUE THREAD

**Issue by probir17** [PeachScript/vue-infinite-loading#224]
```
<infinite-loading 
                                        @infinite="infiniteHandler"
                                        v-if="currentPage > 1"
                                        ref="infiniteLoading"
                                        :distance='300'
                                        :direction="'bottom'"
                                        :spinner='"spiral"'>
                                        <span slot="no-more"></span>
                                        <span slot="no-results"></span>
                                    </infinite-loading>
```
I am getting this issue because i have used ` v-if="currentPage > 1"` this condition.
`currenPage` is my pagination Page number

I used this condition because I have two method `getJobData` and `infiniteHandler` ...at first getJobData run and while scrolling `infiniteHandler` runs. But i found `infiniteHandler` running before `getjobData`.

How do I prevent it from scrolling the page at the beggining or how to add external condition.

Thanks

**Comment by PeachScript** [comment]
`v-if` is the solution, but I don't know why you got error, could you provide a reproduce link?
