### ISSUE TITLE
Scroll 2 pages, then load with button

### ISSUE THREAD

**Issue by wassim** [PeachScript/vue-infinite-loading#229]
Hello, I'm looking to achieve this behaviour; Infinite load 2 pages, then give the user the choice to load 2 more pages everytime via a button.

How can I trigger infiniteLoading on custom event while keeping already loaded pages?

**Comment by PeachScript** [comment]
Hi @wassim , you can implement it via provide a negative `distance` property, maybe this legacy example of the old version doc can help you: https://peachscript.github.io/vue-infinite-loading/old/#!/getting-started/trigger-manually
