### ISSUE TITLE
Auto hiding 'no-more' and 'no-results' messages

### ISSUE THREAD

**Issue by bangjelkoski** [PeachScript/vue-infinite-loading#230]
First of all, thank you for your awesome work on this plugin. 

I would like to ask you if there is a way to auto-hide the *no-more* and *no-results* messages after some time? I dont want to add additional classes to them just for sake of removing them from the DOM using setTimeout when the infinity scroll is completed.

Thank you one more time and have a nice day!

**Comment by PeachScript** [comment]
Glad you like it :D

Of course, you just need to create an empty slot for the specific message type, all details be wrote in the [official docs](https://peachscript.github.io/vue-infinite-loading/guide/configure-load-msg.html#about-hide-default-styles), you can check out it.

Best Regards.
