### ISSUE TITLE
Is this package still actively maintained (or supported)?

### ISSUE THREAD

**Issue by handhikadj** [PeachScript/vue-infinite-loading#231]
Kindly answer this question cause there's many issue that haven't yet answered for a long time

**Comment by louisameline** [comment]
One month is a not such a long time, give him a break.

**Comment by PeachScript** [comment]
Of course yes, but I'm busy at work recently, so the response time maybe long, it would be better if you can create PRs via [Contributing Guide](https://github.com/PeachScript/vue-infinite-loading/blob/master/.github/CONTRIBUTING.md) to contribute this project :)

Thanks a lot for your patience ❤️  @louisameline
