### ISSUE TITLE
How to test infiniteHandler in jest?

### ISSUE THREAD

**Issue by smoothdvd** [PeachScript/vue-infinite-loading#232]
As title

**Comment by PeachScript** [comment]
Emm, in this project, I tested it through trigger the `scroll` event manually, you can check out it in [this test case](https://github.com/PeachScript/vue-infinite-loading/blob/master/test/unit/specs/InfiniteLoading.spec.js#L149), and do you have any idea about this topic?

**Comment by smoothdvd** [comment]
@PeachScript I tested following jest test code and passed:
```
// Mock request load more data(comments)
axios.get.mockResolvedValue({ status: 200, data: mockCommentsMore });
...
wrapper.find(InfiniteLoading).vm.$emit('infinite');
setTimeout(() => {
  expect(wrapper.vm.comments.length).toBe(2);
  expect(wrapper.vm.comments[1].commentID).toBe(2179712);
  done();
}, 10);
```
Do I do the right?

**Comment by PeachScript** [comment]
@smoothdvd  I totally agree with you, because listen scroll event is this plugin's job, so this plugin need to make sure it can convert correctly from scroll event to `infinite` event, for any project that use this plugin, it just need to care about `infinite` event rather than scroll event :P
