### ISSUE TITLE
how can i use the  infiniteloading in a crud after add and edit with a modal component

### ISSUE THREAD

**Issue by giovannyggh** [PeachScript/vue-infinite-loading#233]
hi friend, i'm learning to code and i have a simple crud using vue and laravel, in a parent component i show the data with the infinite loading an it works well:

infiniteHandler($state){
          this.page++
          let urlTask = 'task?page=' + this.page;
          axios.get(urlTask).then(response=>{
            let task = response.data.data
            if(task.length){
               this.tks = this.tks.concat(task);
               $state.loaded()
             }else{
               $state.complete()
             }
          });
         }, 
(this works perfect) now, i have two child components with a modal window (add and edit)
my question is, how can i refresh the new or update data in the parent component with a infiniteloading if i don't use  created: function(){} or mounted? 
thanks

**Comment by PeachScript** [comment]
Maybe you can check out the [Vuex](https://vuex.vuejs.org/) to manage your project data.

**Comment by giovannyggh** [comment]
> Maybe you should to check out the [Vuex](https://vuex.vuejs.org/) to manage your project data.

thanks, bro this component is brillant, i will check Vuex  right now

**Comment by PeachScript** [comment]
You're welcome, glad you like it :D
