### ISSUE TITLE
上一个页面如果有滚动条，并且滚动条滚动了，点击进入列表页就会发起两次请求

### ISSUE THREAD

**Issue by bbbbbboy** [PeachScript/vue-infinite-loading#234]
### Version
v2.4.3
### Vue.js version
v2.x
### Steps to reproduce
vue spa 从一个有滚动条的页面进入到，列表页面，数据有超过一屏
### What is Expected?
应该请求一次接口获取数据
### What is actually happening?
请求了两次获取接口导致数据重复

**Comment by ChenYCL** [comment]
同上述问题，列表长度为0时候请求了两次。
`res => {
            if (res.code == 1000) {
              if (res.data.list.length > 0) {
                for (var o of res.data.list) {
                  self[readyToInsectVariable].push(o);
                }
                $state.loaded();
              } else {
                console.log("done")
                self.emptyBool = true;
                $state.complete();
              }
            }
          }`
当接口第一次返回
内容为{"message":"成功","code":"1000","data":{"list":[],"page":{"currPage":1,"totalCount":0,"totalPage":0,"pageSize":"1"}}}
时候仍然继续请求了一次

**Comment by PeachScript** [comment]
Hi @bbbbbboy @ChenYCL ，此问题应该与 #228 是同一问题，刚刚发布的 [v2.4.4](https://github.com/PeachScript/vue-infinite-loading/releases/tag/v2.4.4) 已对此做了修复，如更新后问题仍然存在，请继续在此讨论

**Comment by june111** [comment]
Hi, 我用的是v2.4.4 用了tab, 请求两次的问题仍然存在

**Comment by xiaotiandada** [comment]
这个问题大家解决了吗 :(

**Comment by blacksunset** [comment]
仍然存在 2.4.4

**Comment by fengfengxia** [comment]
仍然存在

**Comment by lpeihan** [comment]
仍然存在 2.4.4

**Comment by lpeihan** [comment]
是不是可以加个判断，当状态为 loading 的时候不执行 attemptLoad 方法

**Comment by tim0991** [comment]
参考了一下源代码，forceUseInfiniteWrapper 设置为body可以解决 因为动态计算高度带来的加载两次的问题

**Comment by ChangeZhang** [comment]
依然存在
