### ISSUE TITLE
Invalid handler for event "infinite": got undefined

### ISSUE THREAD

**Issue by jonny7** [PeachScript/vue-infinite-loading#237]
Hi

I'm getting the above error and unsure why. It works great in a normal views/some-page.vue. But I'm trying to use it in some sub components listed below.

>Invalid handler for event "infinite": got undefined
> ---> <InfiniteLoading> at InfiniteLoading.vue
>       <CampaignsIndex> at src/views/dashboard/campaigns.vue
>         <BaseDashboard> at src/components/BaseDashboard.vue
>           <DashboardIndex> at src/views/dashboard/default.vue
>             <App> at src/App.vue
>               <Root>

I registered the component like so in **main.js**:
```js
import InfiniteLoading from 'vue-infinite-loading';
Vue.use(InfiniteLoading, {});

```
and call it in my `CampaignsIndex` like so.
```js
<infinite-loading class="col-sm-6 mx-auto" @infinite="infiniteHandler" spinner="waveDots"></infinite-loading>
```
The request goes through and works though fine it seems from the network.

So just wondering, what I've missed here?

**Comment by aholzner** [comment]
Have you defined a method called, "infiniteHandler" in your sub component?

For example:
`
export default {
 methods: {
  infiniteHandler() {
   ....
  }
 }
}
`

You can check out their example: https://peachscript.github.io/vue-infinite-loading/guide/start-with-hn.html

**Comment by jonny7** [comment]
Hi @aholzner 

Yes I have. I should have posted that. The request works when I look at the network request. But I am getting this error in the console and notice that the loading never completes. As in the dots keep bouncing, it never says "No more data :)"

**Comment by jonny7** [comment]
Hi

My bad, I had in my tiredness put this method in `computed`. Thanks for your help :)
