### ISSUE TITLE
向上滚动，如果当前页面只有1条数据如何处理？

### ISSUE THREAD

**Issue by six-666** [PeachScript/vue-infinite-loading#242]
向上滚动，如果当前页面只有1条数据如何处理？

页面初始化时只显示1条数据，往上滚才加载历史记录， 但是只有1条数据时滚动条都没，怎么滚？

**Comment by zb-0819** [comment]
只有一条数据还需要滚动吗

**Comment by six-666** [comment]
@zb-0819 可能没理解清楚，意思是初始化页面只有一条数据，实际上有N条，往上滚才加载历史记录。

**Comment by PeachScript** [comment]
@six-666 数据不够是无法形成滚动的，这其实是个交互设计的问题，如果这些数据不便直接展示，建议提供一个按钮让用户去触发历史数据的加载，可以参考下旧版文档中的 [手动触发加载示例](https://peachscript.github.io/vue-infinite-loading/old/#!/getting-started/trigger-manually)
