### ISSUE TITLE
Using properties?

### ISSUE THREAD

**Issue by vlahde** [PeachScript/vue-infinite-loading#26]
Being a noob in vue.js and infinite loading I have a problem using vue-infinite-loading properties. Here is my code:

`<infinite-loading :on-infinite="onInfinite" ref="infiniteLoading" spinner="circles" distance=99></infinite-loading>`

The spinner definition is fine but distance definition will give me error
`Invalid prop: type check failed for prop "distance". Expected Number, got String. 
(found in component <infinite-loading>)`

Any advice about how to insert numbers as props?

**Comment by PeachScript** [comment]
You can use `v-bind` to change the property type, like this:

```
<infinite-loading v-bind:distance="50"></infinite-loading>
```

or shorhand:

```
<infinite-loading :distance="50"></infinite-loading>
```

Because the data type always be `String` for any custom HTML attribute.

**Comment by PeachScript** [comment]
I will close this issue now, you can reopen it if you need in the future

**Comment by lanmaster53** [comment]
Just ran into this myself. An update to the documentation would probably prevent any future resurfacing of this issue. Thanks!
