### ISSUE TITLE
Create a function and call on change

### ISSUE THREAD

**Issue by Tes3awy** [PeachScript/vue-infinite-loading#264]
Hello @PeachScript ,

I came across your amazing plugin and used it in one of my projects. I am really impressed with your plugin. It's very useful. I'll get straight to the point. I have a dropdown list where each option has to call an API from a server and get some data. How can I run the function on change manually of each dropdown values? I found this [example](https://peachscript.github.io/vue-infinite-loading/old/#!/getting-started/trigger-manually) but couldn't figure out how to use without buttons. Can you assist me in my approach, please? Thanks a lot

**Comment by PeachScript** [comment]
Glad you like it, thanks!

Do you want to use dropdown menu as a filter for list? If yes, you can checkout the [filter demo](https://peachscript.github.io/vue-infinite-loading/guide/use-with-filter-or-tabs.html).
