### ISSUE TITLE
Refresh after new data added

### ISSUE THREAD

**Issue by AO-IO** [PeachScript/vue-infinite-loading#269]
Hi. 
thank you for the package. This package is the best so far for infinite scrolling !!!

I use vue-infinite-loading in my comments component.
usually before using vue-infinite-loading when I add a comment I call a fetch method to see the new data. 

I'm using Laravel.
```JAVASCRIPT
    getComments($state) {
      axios
        .get(`/comment/${this.post}/fetchMore?page=` + this.page)
        .then(
          function(response) {
            if (response.data.data.length) {
              this.page++;
              if (this.comments.length === 0) {
                this.comments = response.data.data;
                console.log("gotten page: " + this.page);
              } else {
                this.comments = this.comments.concat(response.data.data);
              }
              $state.loaded();
            } else {
              $state.complete();
            }
          }.bind(this)
        )
        .catch(function(error) {
          return "There was an error.";
        });
    }
```

```JAVASCRIPT
<infinite-loading @distance="1" spinner="spiral" @infinite="getComments" ref="infiniteLoading">
    </infinite-loading>
```
How is it possible to fetch newly added comments?

 I tried to reset the status in a method  but that didn't work (i saw that in a StackOverflow question)

```JAVASCRIPT
      if (this.$refs.infiniteLoading) {
        return this.$refs.infiniteLoading.stateChanger.reset();
      }
```
I can't figure this out. :\ thank you

**Comment by heidarv** [comment]
Any answer?

**Comment by Sakthi002** [comment]
Any answer???

**Comment by seunafara** [comment]
We need an answer please, how can we recall the function

**Comment by minsoo-web** [comment]
Hey guys @heidarv  @Sakthi002  @seunafara 
I solved this problem by this issue

first, add the ref="infiniteLoading"

<img width="726" alt="스크린샷 2021-03-10 오전 2 04 11" src="https://user-images.githubusercontent.com/57122180/110508931-e97d6300-8144-11eb-96e8-0df4e485bb22.png">

second, call the function when you want

<img width="667" alt="스크린샷 2021-03-10 오전 2 03 54" src="https://user-images.githubusercontent.com/57122180/110508895-dec2ce00-8144-11eb-918e-97954c1758c8.png">

Tada..!

**Comment by JoaoHamerski** [comment]
> Hey guys @heidarv @Sakthi002 @seunafara
> I solved this problem by this issue
> 
> first, add the ref="infiniteLoading"
> 
> <img alt="스크린샷 2021-03-10 오전 2 04 11" width="726" src="https://user-images.githubusercontent.com/57122180/110508931-e97d6300-8144-11eb-96e8-0df4e485bb22.png">
> 
> second, call the function when you want
> 
> <img alt="스크린샷 2021-03-10 오전 2 03 54" width="667" src="https://user-images.githubusercontent.com/57122180/110508895-dec2ce00-8144-11eb-918e-97954c1758c8.png">
> 
> Tada..!

It doesnt work, the person is literally saying that on the screenshot 

> "...that didn't work..."

**Comment by JoaoHCopetti** [comment]
Here is how you can refresh the data of InfiniteScroll:
According to this part of documentation (https://peachscript.github.io/vue-infinite-loading/guide/use-with-filter-or-tabs.html)

Add a `identifier` prop to `InfiniteLoading` component

```lang-html
<InfiniteLoading 
    :identifier="infiniteId"
    @infinite="infiniteHandler"
></InfiniteLoading>
```
Add the `infiniteId` data to your component `data`:
```lang-js
data: function() {
    return {
        list: [],
        infiniteId: +new Date() // It will generate a random value based on current time
    }
}
``` 
Add a new method into your Vue component, i will call it `refreshInfiniteLoading`
```lang-js
methods: {
    refreshInfiniteLoading() {
        this.page = 1
        this.list = []

        // as said in the documentation 
        // "The infinite loading component will 
        // reset itself whenever the identifier property has changed"
        this.infiniteId += 1 
      },
}
```

Every time you want to refresh your data just call `refreshInfiniteLoading` method.
