### ISSUE TITLE
How can I use two vue-infinite-loading in one html

### ISSUE THREAD

**Issue by ivipllp** [PeachScript/vue-infinite-loading#27]
I am a beginner in vue. Now I want to use  two vue-infinite-loading in one html. But I don't know how to do it.

**Comment by PeachScript** [comment]
The key point is passing event for the multiple components, all right?

You can use the `ref` official directive to get the instance of every `infinite-loading` component and emit event by it, to passing event for your specific component.

Hope can help you!

**Comment by ivipllp** [comment]
Thank you!  I have solved this problem with your help. But it does not seem to work in WeChat browser. How can I do? Thanks.

**Comment by PeachScript** [comment]
Maybe you can debug it with this tool: [Wechat Developer Tool](https://mp.weixin.qq.com/wiki/10/e5f772f4521da17fa0d7304f68b97d7e.html)

**Comment by ivipllp** [comment]
But the loading spinner doesn't work in my mobile phone (meizu Pro 6). And I can't find the style of spinner

**Comment by PeachScript** [comment]
I will close this issue now, you can reopen it if you need in the future.

**Comment by AyushiBShah** [comment]
@PeachScript : You can use the ref official directive to get the instance of every infinite-loading component and emit event by it, to passing event for your specific component.

By above statement do we mean to pass $state.loaded and $state.complete in respect to `ref` attribute somehow ? Can you please help me with a small snippet?
