### ISSUE TITLE
Customize styles?

### ISSUE THREAD

**Issue by rorc** [PeachScript/vue-infinite-loading#28]

**Comment by PeachScript** [comment]
Could you provide any more information?

**Comment by rorc** [comment]
Customize all files in `vue-infinite-loading/src/styles/` with variables?

**Comment by PeachScript** [comment]
All the styles be written for the [Spinners](https://peachscript.github.io/vue-infinite-loading/#!/spinners), if you don't like them, you can customize your own spinner with the `spinner` slot, so I think you needn't customize all files in `vue-infinite-loading/src/styles/`, is that right?

**Comment by rorc** [comment]
And if i want to customize available spinners without creating new my spinners? )

**Comment by PeachScript** [comment]
Of course you can, just need add a custom class name on some preset spinner with the `spinner` slot, for example:

```html
<vue-infinite-loading>
  <span slot="spinner">
    <i class="loading-circles custom-spinner"></i>
  </span>
</vue-infinite-loading>
```

And override some styles which you need:

```css
.loading-circles.custom-spinner {
  /* your custom styles */
}
```

**Comment by rorc** [comment]
Yes, but its unecessary and dirty (

**Comment by PeachScript** [comment]
I think it's simple, I just need to override part of the styles, maybe you have a better way?

**Comment by rorc** [comment]
Maby need as bootstrap, with create file with all variables with `!default` and i can include this file after defining my own variables.
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_variables.scss

**Comment by PeachScript** [comment]
It's really a better way to customize styles, because of the `BootStrap` is a general-purpose UI framework, but the core of this component is provide a convenient way to implement infinite scroll list, so I think this feature is unnecessary.
