### ISSUE TITLE
Error after updating Vue to v2.1.5

### ISSUE THREAD

**Issue by junyik** [PeachScript/vue-infinite-loading#29]
The following error was triggered after Vue has been updated to [v2.1.5](https://github.com/vuejs/vue/releases/tag/v2.1.5).

![error](https://cloud.githubusercontent.com/assets/23161630/21142103/9220e960-c10e-11e6-9ad5-29c0873466f4.png)

Thank you.

**Comment by RDelorier** [comment]
This is also happening in vuex-toast so I think its a problem with the 2.1.5 release

**Comment by junyik** [comment]
Agreed, and it looks like they've just released [v2.1.6](https://github.com/vuejs/vue/releases/tag/v2.1.6).

Errors are the same for [v2.1.6](https://github.com/vuejs/vue/releases/tag/v2.1.6).
![error](https://cloud.githubusercontent.com/assets/23161630/21151948/62ca0182-c132-11e6-99a6-2e1f084508ff.png)

**Comment by icyfire** [comment]
Same issue.Need to fallback to v2.1.4.

**Comment by RDelorier** [comment]
I believe you just need to rebuild the dist, looks like this is the culprit https://github.com/vuejs/vue/commit/4b51ad048306367a6fb6fbee7445e086d855f31e

**Comment by PeachScript** [comment]
Thank you all very much! I already rebuild it with the latest `vue-template-compiler` and release a new version [v2.0.0-rc.4](https://github.com/PeachScript/vue-infinite-loading/releases/tag/v2.0.0-rc.4), you can upgrade it with `npm`, please tell me if it still has problem :P

**Comment by junyik** [comment]
Thank you @PeachScript @RDelorier. I have tested [vue-infinite-loading@2.0.0-rc.4](https://github.com/PeachScript/vue-infinite-loading/releases/tag/v2.0.0-rc.4) with[ vue@2.1.6](https://github.com/vuejs/vue/releases/tag/v2.1.6) and they are working great! 👍 

![result](https://cloud.githubusercontent.com/assets/23161630/21183342/7a632942-c1d5-11e6-90fc-68150fb44c5e.png)
