### ISSUE TITLE
组件一直无限加载，是哪地方写法有问题吗

### ISSUE THREAD

**Issue by xwyjh-qd** [PeachScript/vue-infinite-loading#294]
`<template http-equiv="Access-Control-Allow-Origin" content="*">
  <div class="ul">
    
    <infinite-loading
      @infinite="infiniteHandler"
      force-use-infinite-wrapper=".ul"
    >
      <div slot="no-more">没有更多消息</div>
      <div slot="no-results"></div>
    </infinite-loading>
    <div class="li" v-for="(item, index) in list" :key="index">
      <span>{{ item }}</span>
    </div>
    
  </div>
</template>

<script>
import InfiniteLoading from "vue-infinite-loading"; // 滚动加载 https://peachscript.github.io/vue-infinite-loading/guide/#import

export default {
  name: "ChatMessage1",
  components: { InfiniteLoading },
  data() {
    return {
      num: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      list: []
    };
  },

  methods: {
    infiniteHandler($state) {
      setTimeout(() => {
        this.list.push(this.num);
        console.log("--------------");
        $state.loaded();
      }, 1000);
    }
  }
};
</script>

<style scoped>
.ul {
  display: flex;
  flex-direction: column;
  height: 100%;
  overflow-x: hidden;
  overflow-y: auto;
}
.li {
  width: 100%;
  height: 100px;
  margin: 4px 0;
  flex-shrink: 0;
  background-color: #eee;
}
</style>
`

**Comment by roma219** [comment]
🤦
