### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by asafyish** [PeachScript/vue-infinite-loading#299]
Hi,

Vue 3 is out for several weeks now, is there a plan to support it ?

**Comment by samuveth** [comment]
Any progress here?

**Comment by hoomb** [comment]
+1

**Comment by rafaelmagalhaes** [comment]
has anyone managed to use it with the composition api

**Comment by nVitius** [comment]
I worked on this a bit today: https://github.com/nVitius/vue-infinite-loading/tree/next

I haven't tested everything but the core functionality at least is working.
I didn't try running the tests, but I'm pretty sure they aren't valid anymore.

I switched webpack out for rollup and used [this project](https://github.com/team-innovation/vue-sfc-rollup) to configure the build process.

Until this is merged, you should be able to install it with npm like this:
`npm i --save github:nvitius/vue-infinite-loading#next`

Usage is the same as before.

**Comment by joaomirandas** [comment]
+1

**Comment by wobsoriano** [comment]
You can use this inside a Vue 3 app via https://github.com/privatenumber/vue-2-3

Here's a working example https://codesandbox.io/s/vue3-infinite-loading-63rqj

https://github.com/wobsoriano/vue3-infinite-loading

**Comment by productdevbook** [comment]
https://github.com/PeachScript/vue-infinite-loading/issues/313#issuecomment-871106685
