### ISSUE TITLE
Cannot read property 'removeEventListener' of null

### ISSUE THREAD

**Issue by daneric** [PeachScript/vue-infinite-loading#3]
when loaded list is empty, it throw an error: Cannot read property 'removeEventListener' of null, and never load again event fresh this page

**Comment by PeachScript** [comment]
This component will call `removeEventListener` in the following situations:
1. Received `$InfiniteLoading:noResults` event;
2. Received `$InfiniteLoading:noMore` event;
3. Component be destroyed by something, for example `v-if`.

So, what did you do before it throw the error?

**Comment by PeachScript** [comment]
A week passed and no reply, I will close the issue.
