### ISSUE TITLE
Slots seem to be not working in vue@2.1.7

### ISSUE THREAD

**Issue by icyfire** [PeachScript/vue-infinite-loading#31]
It doesn't work as expected in vue@2.1.7, and only displays text 'undefined'.

**Comment by PeachScript** [comment]
Is it like #30 ?

**Comment by PeachScript** [comment]
You both reported the same issue, maybe I missed some details, could you paste your code here?

**Comment by icyfire** [comment]
The code is quite simple.

`
<infinite-loading :on-infinite="onInfinite" ref="infiniteLoading">
    <p slot="no-more">No more data</p>
    <p slot="no-results">No results</p>
</infinite-loading>
`
Normally,it should display "No more data" when there is no more data or display "No results" where there is no results.But in vue@2.1.7,what i really got is "undefined".

**Comment by icyfire** [comment]
The code is quite simple.

`<infinite-loading :on-infinite="onInfinite" ref="infiniteLoading">
  <p slot="no-more">No more data</p>
  <p slot="no-results">No results</p>
</infinite-loading>`

Normally,it should display "No more data" when there is no more data or display "No results" where there is no results.But in vue@2.1.7,what i really got is "undefined".

**Comment by icyfire** [comment]
The code is quite simple.

```
<infinite-loading :on-infinite="onInfinite" ref="infiniteLoading">
  <p slot="no-more">No more data</p>
  <p slot="no-results">No results</p>
</infinite-loading>
```

Normally,it should display "No more data" when there is no more data or display "No results" where there is no results.But in vue@2.1.7,what i really got is "undefined".

**Comment by PeachScript** [comment]
According to your description I try to repeat it in my computer, but it still running well, could you repeat it on [JsFiddle](http://jsfiddle.net/) and discuss it in #30?

I will close the duplicate issue, thank you very much!
