### ISSUE TITLE
Working example in Vue 3

### ISSUE THREAD

**Issue by wobsoriano** [PeachScript/vue-infinite-loading#314]
With the help of [this library](https://github.com/privatenumber/vue-2-3), you can interop Vue 2 components in Vue 3 apps and vice versa.

A very basic hackernews app: https://codesandbox.io/s/vue3-infinite-loading-63rqj

Repo: https://github.com/wobsoriano/vue3-infinite-loading

**Comment by productdevbook** [comment]
https://github.com/PeachScript/vue-infinite-loading/issues/313#issuecomment-871106685
