### ISSUE TITLE
Loading only unfefined with vue 2.1.7

### ISSUE THREAD

**Issue by dinho-afsn** [PeachScript/vue-infinite-loading#32]
Is not working with version 2.1.7 of vue.
all work, but spinner undefined

here my code

package.json
"vue": "2.1.7",
"vue-infinite-loading": "next"

component:

`
<template>
	<div>
		<section class="grig-home">
			<div class="container">
				<div class="row">
					<div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 item-grid" v-for="list in lists">
						<img :src="list._source.imagem" class="img-responsive img-grid">
						<infinite-loading :on-infinite="onInfinite" ref="infiniteLoading" spinner="spiral">
						</infinite-loading>
					</div>

				</div>
			</div>
		</section>
	</div>
</template>
<style>
</style>
<script type="text/babel">
 	let api = ' url my api'
	export default {
		data() {
			return {
				lists: [],
			}
		},
		methods: {
			onInfinite() {
				this.$Progress.start()
				this.$http.get(api, {params: {page: this.lists.length / 3}}).then((response) => {
					if (response.data.hits.hits.length) {
						this.lists = response.data.hits.hits
						window.console.log(this.lists)
						this.$refs.infiniteLoading.$emit('$InfiniteLoading:loaded')
						if (this.lists.length === 2) {
							this.$refs.infiniteLoading.$emit('$InfiniteLoading:complete')
						}
					} else {
						this.$refs.infiniteLoading.$emit('$InfiniteLoading:complete')
					}
				}, (error) => {
					this.$Progress.fail()
					window.console.log(error)
				});
			},
			start () {
				this.$Progress.start()
			},
			set (num) {
				this.$Progress.set(num)
			},
			increase (num) {
				this.$Progress.increase(num)
			},
			decrease (num) {
				this.$Progress.decrease(num)
			},
			finish () {
				this.$Progress.finish()
			},
			fail () {
				this.$Progress.fail()
			},
		},
		components: {
			InfiniteLoading,
		},
	};
</script>`

**Comment by dinho-afsn** [comment]
Have I tried everything
Use a normal attribute:
<infinite-loading :on-infinite="onInfinite" spinner="spiral" ref="infiniteLoading"></infinite-loading>
Use a string:
<infinite-loading :on-infinite="onInfinite" :spinner="'spiral'" ref="infiniteLoading"></infinite-loading>
Use a variable:
<infinite-loading :on-infinite="onInfinite" :spinner="spinnerType" ref="infiniteLoading"></infinite-loading>



all undefined in spinner

**Comment by PeachScript** [comment]
I think this issue same as #30 , but I cannot repeat the problem in my computer, could you repeat it on [JsFiddle](http://jsfiddle.net/) and discuss it in #30? I will close the repeated issue.
