### ISSUE TITLE
On mobile screen, the vue-infinite-loading auto load all records without scrolling?

### ISSUE THREAD

**Issue by cuoppro9x** [PeachScript/vue-infinite-loading#321]
Hello, I have a problem.
.
The vue-infinite-loading works normally on Desktop screen size. (it only loads the next records when I scroll to the bottom of the screen)
.
But
.
On tablet or mobile screen size, it automatically loads all the next records until there's no record to load although I don't scroll to the bottom of the screen. That's make my web call too many API automatically and slowy.
.
Here is my example code:

`infiniteHandler($state: StateChanger): void {
    if (this.totalPageCnt < this.pageID) {
      $state.complete();
      return;
    }
    const payload =
      this.channelId === 'bookmark'
        ? { pageId: this.pageID, cnt: 1 }
        : {
            pageId: this.pageID,
            cnt: 1,
            contentsType: this.channelId ? [Number(this.channelId)] : [],
          };
    ArticleStateModule.loadPageAndStore(payload)
      .then(() => {
        $state.loaded();
        this.$emit('loadingChange', false);
      })
      .catch((e) => {
        this.$emit('loadingChange', false);
        CONSTANTS.APP_ERROR.NO_DATA === e ? $state.complete() : $state.error();
      });
  }`

Video: [https://watch.screencastify.com/v/mxyYiD1i1Tfs6CzTc29O](https://watch.screencastify.com/v/mxyYiD1i1Tfs6CzTc29O)

Hope you support me soon. Thanks.
.
Sorry for my bad English

**Comment by ChananyaWinston** [comment]
I'm experiencing the same issue
Why did you mark this issues as completed

**Comment by mor-thuongnd** [comment]
> I'm experiencing the same issue Why did you mark this issues as completed

[ChananyaWinston](https://github.com/ChananyaWinston)
I found my problem is because of my css, not because of this component. - I'm **cuoppro9x**

**Comment by ChananyaWinston** [comment]
Thank you. I found that too

**Comment by Shaikh-Dilshad** [comment]
[ChananyaWinston](https://github.com/ChananyaWinston)
can you tell  me which css is affecting this?
