### ISSUE TITLE
With vuefire the infinitescroll keeps running

### ISSUE THREAD

**Issue by xerosanyam** [PeachScript/vue-infinite-loading#37]
I wanted to get more elements from firebase when scrolled to bottom of a page, however it keeps running the onInfinite method.

**Comment by PeachScript** [comment]
Could you paste your code on [JSFiddle](https://jsfiddle.net/)?

**Comment by PeachScript** [comment]
22 days passed and no reply, I will close the issue, you can reopen it if you need.
