### ISSUE TITLE
lack of css prefix in the dist file

### ISSUE THREAD

**Issue by Hanruis** [PeachScript/vue-infinite-loading#38]
i found that  dist file lack of css prefix .... and  in some android  browser ..the spinner animation not work ..
android  4.4 , and some customized rom by android 5.0...

i need to build it by my self ?
(sorry my poor English)

**Comment by PeachScript** [comment]
I see, you mean the CSS3 specific browser prefixes, I will fix it through a patch version, thanks!

By the way, my English is also poor, mutual encouragement 😄

**Comment by Hanruis** [comment]
thx a lot...

**Comment by PeachScript** [comment]
I have been published a new version to fix it, please upgrade it and try again @Hanruis

**Comment by Hanruis** [comment]
dist 文件里面，并没有看到 prefixes 的影子。

**Comment by PeachScript** [comment]
Sorry, I make a mistake, please use v2.0.2 instead.

**Comment by Hanruis** [comment]
thanks, it works perfect
