### ISSUE TITLE
this.$refs.infiniteLoadin

### ISSUE THREAD

**Issue by 646114800** [PeachScript/vue-infinite-loading#39]
the 'this.$refs.infiniteLoadin' is a Array, not a VueComponent;

error:  this.$refs.infiniteLoading[0].$emit(......)  not is a Function

success: try 'this.$refs.infiniteLoading[0].$emit(......)'

**Comment by PeachScript** [comment]
Could you paste your code in [JSFiddle](https://jsfiddle.net/) or any website like it?

Your can include this plugin by [rawgit.com](https://rawgit.com/PeachScript/vue-infinite-loading/master/dist/vue-infinite-loading.js) in your JSFiddle.

**Comment by PeachScript** [comment]
I will close this issue, you can reopen it if you need in the future.
