### ISSUE TITLE
Issue in the Hacker News Demo Code

### ISSUE THREAD

**Issue by prcvoldermort** [PeachScript/vue-infinite-loading#41]
if (this.list.length / 20 === 10) {
            this.$refs.infiniteLoading.$emit('$InfiniteLoading:complete');
          }
        } else {
          this.$refs.infiniteLoading.$emit('$InfiniteLoading:complete');
        }

In the else branch, the parameter in the $emit() function should be '$InfiniteLoading:loaded', I suppose, or the loading is done in the beginning.

**Comment by PeachScript** [comment]
Nope, the else branch is associated with `if (res.data.hits.length)` not `if (this.list.length / 20 === 10)`.

**Comment by prcvoldermort** [comment]
I see... Sorry for the misunderstanding.
