### ISSUE TITLE
infiniteLoading is not defined

### ISSUE THREAD

**Issue by imkimchi** [PeachScript/vue-infinite-loading#42]
This error occurs when It runs the code below
`this.$refs = infiniteLoading.$emit('$InfiniteLoading:loaded')`
I have no idea why It occurs reference error. because I literally see the loading infinite-loading element which shows loading animation at the bottom of my page. but the thing is that It doesn't load infinitely, It just load everything and shows only loading element.

**Versions**
```
"vue": "^2.2.1",
"vue-infinite-loading": "^2.0.4",
"vue-loader": "^11.1.4",
"webpack": "^2.3.2"
```

**Code**
```
  import InfiniteLoading from 'vue-infinite-loading'

  export default {
      name: 'main',
      
      data: () => ({
        items: [],
        lines: 0,
      }),
      
      async created () {
        this.items = await fetch('/videos').then(res => res.json())
      },

      computed: {
          columns: function() {
              return chunk(this.items, 4)
          }
      },
    
      methods: {
        onInfinite() {
          setTimeout(() => {
            const temp = []
            const len = this.columns.length
            for (let i = len + 1; i <= len + 20; i++) {
              temp.push(columns[i])
            }
            this.columns = this.columns.concat(temp)
            this.$refs = infiniteLoading.$emit('$InfiniteLoading:loaded')

          }, 700)
        },
      },
      
      components: {
        InfiniteLoading
      },
```

**Comment by PeachScript** [comment]
Hi @imkimchi , `$refs` is an [official property](http://vuejs.org/v2/api/#vm-refs) of Vue instance, through it we can get child component instances that have `ref` registered. In this case, we use to `$emit` event to the `InfiniteLoading` instance. So the code should like this:

template:
```html
<infinite-loading ref="myRefName"></infinite-loading>
```

script:
```js
export default {
  ...
  methods: {
    onInfinite() {
      ...
      this.$refs.myRefName.$emit('$InfiniteLoading:loaded');
      ...
    },
  },
  ...
}
```

Hope to help you.

**Comment by PeachScript** [comment]
27 days passed but no reply, I will close this issue, you can reopen it if you need in the future.
