### ISSUE TITLE
vue-scrollbar with infinite loading

### ISSUE THREAD

**Issue by cristiandan** [PeachScript/vue-infinite-loading#45]
Hello,
I want to use https://github.com/BosNaufal/vue2-scrollbar with vue-infinite-loading but I can't get it to work. When I get to the top of scrollable area the infinite loading doesn't load anymore. If I user basic html instead, it works. Can you help me please?

**Comment by joelcuevas** [comment]
I think this is the same as #44, as vue2-scrollbar sets the overflow to "hidden" on the scrollable container.

**Comment by PeachScript** [comment]
Yep, let's discuss it in #44, I will close this issue. @cristiandan @joelcuevas
