### ISSUE TITLE
The broadcast of $ broadcast ('$ InfiniteLoading: reset') takes effect

### ISSUE THREAD

**Issue by millertiga** [PeachScript/vue-infinite-loading#46]
In the use of this. $ Broadcast ('$ InfiniteLoading: reset'), the normal operation of the initialization, but in the modified filter conditions, the reset operation, change the statement does not take effect, but again modify the filter conditions, reset again run. That is, the sentence interval takes effect.

![image](https://cloud.githubusercontent.com/assets/21698240/25798013/26bd4f52-3412-11e7-9fd2-622fe7373f3e.png)

![image](https://cloud.githubusercontent.com/assets/21698240/25798049/3f1f591e-3412-11e7-90d5-2c94c3509418.png)

![image](https://cloud.githubusercontent.com/assets/21698240/25798065/4bd660bc-3412-11e7-872f-97fe86de5081.png)

![image](https://cloud.githubusercontent.com/assets/21698240/25798089/6074acae-3412-11e7-9e14-6e4d16e8d863.png)

![image](https://cloud.githubusercontent.com/assets/21698240/25798121/82a146c0-3412-11e7-9d2a-51464d9ad557.png)

**Comment by PeachScript** [comment]
I guess the reset function does not work properly, could you paste your code on [JSFiddle](https://jsfiddle.net/) or other website like it?

**Comment by millertiga** [comment]
https://jsfiddle.net/60tokjr0/1/

**Comment by PeachScript** [comment]
Okay, but I cannot found the element which calling the `reset` function, and this demo cannot running well.

Please reproduce your problem in the demo, thanks!

**Comment by PeachScript** [comment]
12 days passed but no reply, I will close this issue, you can reopen it if you need in the future.
