### ISSUE TITLE
Scroll event performance optimization 

### ISSUE THREAD

**Issue by syn-zeta** [PeachScript/vue-infinite-loading#49]
The scroll event currently triggers a relatively expensive operation: `attemptLoad`, and thus, `getCurrentDistance` which uses `getBoundingClientRect` a couple of times that will require a recalculation of the layout of the DOM.

The number of calls to `attemptLoad` can be significantly reduced by using a simple [debounced](https://davidwalsh.name/javascript-debounce-function) scrolling handler.

Without `debounce` (`console.count()` in `attemptLoad()`):
![out_1](https://cloud.githubusercontent.com/assets/26761352/26182806/71646c4c-3b2f-11e7-9bc8-e606c2f15de2.gif)

With `debounce` (timeout of `50ms`):
![scroll_2](https://cloud.githubusercontent.com/assets/26761352/26182344/94552a8c-3b2c-11e7-9ef1-ca3c74a2e9d7.gif)

The scope of change is very minor. Would a PR for this be acceptable?

**Comment by PeachScript** [comment]
Hi @syn-zeta , [v2.2.0](https://github.com/PeachScript/vue-infinite-loading/releases/tag/v2.2.0) has been released, contains the performance optimization, thank you very much!

**Comment by syn-zeta** [comment]
Looks great, thanks!
