### ISSUE TITLE
Ajax call

### ISSUE THREAD

**Issue by almaweb** [PeachScript/vue-infinite-loading#5]
How to use this with dynamique data ?
Merci

**Comment by PeachScript** [comment]
You're welcome.

Please see the example code [click here](https://github.com/PeachScript/vue-infinite-loading/blob/master/example/index.html), replace the `setTimeout` with your ajax statements, this component will work with dynamic data.

**Comment by almaweb** [comment]
Merci for your reply
But i am not expert with vue.js so....
I tried this but seems that i miss something
  <script>
    new Vue({
      el: '#app',
      data: {
        distance: 100,
        list: [],
        videos: []  
      },
      ready: function () {
        var vm  = this;
        var apiURL = '/api/api-all-video'
        $.get( apiURL, function( response ) {
            vm.videos = response.data;
            for (var i = 0; vm.videos.length < 6; i++) {
              vm.videos.push(response.data);
            }
        });

      },
      methods: {
        onInfinite: function () {
        var vm  = this;
        var apiURL = '/api/api-all-video'
        $.get( apiURL, function( response ) {
            vm.videos = response.data;
            for (var i = 0; vm.videos.length < 6; i++) {
              vm.videos.push(response.data);
            }
           vm.videos = vm.videos.concat(vm.videos);
        });

        }
      }
    });
  </script>

**Comment by PeachScript** [comment]
You forgot to `$broadcast` an `$InfiniteLoading:loaded` event to this component, you can try the following pseudo code:
```
onInfinite: function () {
  var vm = this;
  $.get(api, function (res) {
    vm.videos = vm.videos.concat(res.data);
    vm.$broadcast('$InfiniteLoading:loaded');
  });
}
```

Maybe can help you.

**Comment by PeachScript** [comment]
Two weeks passed and no reply, I will close the issue.
