### ISSUE TITLE
在路由切换的时候怎么重置(no-data)complete状态呢

### ISSUE THREAD

**Issue by shuangbofu** [PeachScript/vue-infinite-loading#52]
index页面加载完毕，$emit('$InfiniteLoading:complete')后，切换到profile，再切回index还是显示no-data，如果使用$emit('$InfiniteLoading:reset')的话，又会将之前所有的数据加载全部加载一遍，而实际上只需要加载15条数据，也就是一次加载(刷新)

**Comment by PeachScript** [comment]
一旦 `complete` 就说明此列表已经完成加载，为什么回到 index 还需要再次加载 15 条数据？

**Comment by PeachScript** [comment]
回到问题本身，`$emit('$InfiniteLoading:reset')` 仅仅是将组件重置为初始化状态并立即进行一次距离检测，如果距离符合预期那么立即触发一次 `onInfinite` 函数，加载的数据内容是由实际的 `onInfinite` 函数决定的而不是这个组件，也就是说倘若你希望只在 `reset` 之后增量加载 15 条数据，在 `onInfinite` 函数中做相应处理即可。

**Comment by shuangbofu** [comment]
是这样的，进入index页之后，分别加载15条、下拉加载又15条、下拉加载又9条，然后没数据了，后台的所有数据加载完毕。之后转到profile页。再转回index页的时候需求是重新加载最新的15条。

而使用了这个组件，回到index，只是加载了15条但显示加载完毕，无法再继续加载。也就是说那个no-data状态依然存在。

**Comment by shuangbofu** [comment]
相当于浏览新闻
最初加载15条新闻，然后用户下拉继续加载，继续浏览，之后用户转到个人页再转回新闻页的时候需要显示最新的15条新闻，而且可以继续下拉
而现实是此时15条新闻最下面显示的是no-data，不能下拉加载

**Comment by PeachScript** [comment]
如果你期望的结果是用户从其他页面回到 index 之后的状态和第一次进入 index 时候的状态完全一致的话，我推测你启用了 [`keep-alive`](http://vuejs.org/v2/api/#keep-alive) 特性，关掉就行了；

如果你期望的结果是用户从其他页面回到 index 时仍旧是离开时的状态但可以继续加载数据，那么回来的时候 `reset` ，然后像我上一条回复中描述的那样利用 `onInfinite` 函数加载数据即可。

**Comment by shuangbofu** [comment]
但是这样的话，每次切换，index页面就都重新created了，相当于刷新页面了

**Comment by shuangbofu** [comment]
进入detail或者其他页面，然后再出来，index页面就刷新了，

我想做的是在index离开到--->profile的时候更新数据，然后切回去的时候数据就更新了，还可以下拉加载

比如可以看[http://scuinfo.com]的network数据获取，从index--->detail的时候没有更新index页的数据，而index--->profile的时候更新数据，而返回的时候index依然可以下拉加载更多

**Comment by PeachScript** [comment]
抱歉，看了一下你提供的网站，确实没能理解你遇到的问题具体是什么。倘若问题是由于这个插件的缺陷引起的，烦请使用类似于 [JSFiddle](https://jsfiddle.net/) 之类的平台进行问题重现，以便于我们进一步分析问题产生的原因；若是业务需求实现相关的问题，我想 StackOverflow 或者 SegmentFault 之类的问答社区会比 GitHub 的 issue 更加适合。

**Comment by shuangbofu** [comment]
好的，谢谢大神耐心解答了，打扰了
