### ISSUE TITLE
scrolll with vue router problem on phone

### ISSUE THREAD

**Issue by athemb** [PeachScript/vue-infinite-loading#53]
Hi, I have a problem with the scroll when I am on a page with a long content, I change page with vue router, the scroll does not work very well, very long to load, and does not detect all the time Bottom of the document. By cons if I arrive directly on the page with the scroll its works very well. The problem is only on phone and tablet on pc no problem, thank for you help.

**Comment by PeachScript** [comment]
Please reproduce your problem on [JSFiddle](https://jsfiddle.net) or other website like it if this problem can be reproduce in browser's simulator.

**Comment by PeachScript** [comment]
1 month passed but no reply, I will close this issue, you can reopen it if you need in the future.
