### ISSUE TITLE
event listener scroll not working on mobile

### ISSUE THREAD

**Issue by jernejrostan** [PeachScript/vue-infinite-loading#54]
Hi,

I cant get to work infinite loading on any mobile device, as i am debugging, scroll event is never fired on any mobile device, so it does not know when do we reach to end of the document.

Or maybe i am doing something wrong, but i am loading everything as per manual.

Is that a known issue? I am only testing this with Vue1 for now

**Comment by PeachScript** [comment]
But it works well on my mobile phone, could you reproduce your problem on JSFiddle or other website like it if this problem can be reproduce in browser's simulator?

**Comment by jernejrostan** [comment]
Nop, cant reproduce the issue on JSFiddle, sorry

I did however used source code and put some console.logs in it ... as i scroll on mobile or in browser simulator, distance is not calculated ... Is there something that i missed, maybe some overflow with CSS that is disabling stuff?

**Comment by PeachScript** [comment]
This plugin will think of the body as the scroll parent if it does not has any `overflow: auto|scroll` parent element, so the CSS style is not necessary.

By the way, will it be reproduced on JSFiddle if open browser simulator? If not, you can paste your key on the JSFiddle even it does not work properly.

**Comment by PeachScript** [comment]
1 month passed but no reply, I will close this issue, you can reopen it if you need in the future.
