### ISSUE TITLE
reset event does not always trigger the on-infinite method

### ISSUE THREAD

**Issue by syn-zeta** [PeachScript/vue-infinite-loading#56]
[Documentation for $InfiniteLoading:reset](https://peachscript.github.io/vue-infinite-loading/#!/events) (emphasis mine):
>The `InfiniteLoading` component will back to the original state, _and the `on-infinite` function will be called immediately_.

As we can see at https://jsfiddle.net/ezpnr4q8/3/, it is not the case.

`reset` calls `scrollHandler` which, in turn, calls `attemptLoad` that will invoke `on-infinite` only if the infinite-loaded list does not have enough items. This works well if the already loaded data is cleared along with resetting this component, [as in the demo](https://peachscript.github.io/vue-infinite-loading/#!/getting-started/with-filter).

In my use case, the loaded data is filtered, but not completely cleared, so `on-infinite` is not called as long as there's one page of data. It'd be great to have an optional parameter when triggering a `reset` to "force" a refresh, and definitively call `on-infinite`.

**Comment by PeachScript** [comment]
The documentation is really wrong, I will fix it, thanks!

But I think the force refresh is not a good solution, because as long as there has data that means the list has not been reset. Maybe change the filter then load data manually through the `on-infinite` function is a better way, how do you think about it?

**Comment by syn-zeta** [comment]
Yes, that is certainly a simple solution that I had considered. The reason why I created this issue is because I felt that my use case is perhaps common: clearing the data completely when applying a filter is a jarring user experience, so having an option to filter on the client-side but still refresh the data with the filter applied would be great.

Vue allows passing arguments with events, and the proposed `force` parameter would be optional to not affect the existing behavior.

But I can understand if you would not like to include this in the component.

**Comment by PeachScript** [comment]
Sorry to reply so late, and thank you very much for your understanding! Because of I have a little OCD for coding, I hope every API is no ambiguity, forgive me, aha. I will add more details for the reset event document.

Best regards.

**Comment by syn-zeta** [comment]
It's all good. Thanks for your consideration.
