### ISSUE TITLE
如何阻止 on-infinite 连续触发呢？

### ISSUE THREAD

**Issue by syaka-yin** [PeachScript/vue-infinite-loading#6]
如果用户停留在列表底部，会连续触发 on-infinite 事件，请问这个问题应该如何阻止呢？

**Comment by PeachScript** [comment]
触发的流程大致如下：
1. 滚动到底部
2. 触发 `on-infinite` 函数
3. `on-infinite` 函数获取数据，在获取完毕后发送 `$InfiniteLoading:loaded` 事件告诉组件数据加载完毕
4. 等待下一次触发

所以按照逻辑看来连续触发应该是不会产生的。如果希望了解使用的 demo 或者文档，可以访问：[https://peachscript.github.io/vue-infinite-loading/](https://peachscript.github.io/vue-infinite-loading/) 查看 example。

如果依然无法解决你的问题，可以详细描述之后贴到该 issue，看看是不是由于组件的 bug 导致该问题的产生。

**Comment by syaka-yin** [comment]
如果用户停留在底部，那么源码中的 currentDistance <= this.distance 条件是一直满足的，结果就会导致一直运行 this.onInfinite.call()
希望能看一看这个问题

**Comment by PeachScript** [comment]
距离判断只会在用户触发`scroll`这个事件之后才会执行，如果只是“停留”在底部，是不会触发`scroll`这个事件的，也就更加不会去判断距离了。所以，你不妨检查一下是不是有地方导致该容器元素一直在进行滚动。

**Comment by PeachScript** [comment]
一个星期过去了但未收到任何新的回复，我将会关闭此 issue。
