### ISSUE TITLE
Hide slot "no-more" option

### ISSUE THREAD

**Issue by vgladimir** [PeachScript/vue-infinite-loading#61]
Hello,

In my app I don't need any "no-more" message. How to hide this slot in normal way?

**Comment by PeachScript** [comment]
You can simply override it through a blank element:

```html
<infinite-loading>
  <span slot="no-more"></span>
</infinite-loading>
```

**Comment by vgladimir** [comment]
Yes, but how about extra style on ```.infinite-status-prompt```.

![2017-07-17 9 41 58](https://user-images.githubusercontent.com/19341468/28257678-406355b0-6ad5-11e7-8a2e-bfb2d2a37153.png)

**Comment by PeachScript** [comment]
Oh...It's really difficult, this part of the code has side-effect, so I must optimize it in the next version. For now, you can override the styles of `.infinite-status-prompt` in your code, it's a temporary solution, how do you think?

**Comment by vgladimir** [comment]
For temporary solution I will do it. Okey, I am waiting for a update.

**Comment by PeachScript** [comment]
Hi @vgladimir , [v2.2.0](https://github.com/PeachScript/vue-infinite-loading/releases/tag/v2.2.0) has been released, include the slot hide feature, you can try it now, please feedback to here if you find any problem, thanks :D

**Comment by Sinled** [comment]
Hi, i have a little different case,
i want to render custom markup inside slots not just text, and in this case i should manually reset inherited styles,
is there more convenient solution?

**Comment by PeachScript** [comment]
Not yet, you must override the inherited styles currently, it is another problem, we can discuss in #80

**Comment by hardik-baraiya-123456** [comment]
```
<InfiniteLoading @infinite="load">
          <template #complete><div></div></template>
        </InfiniteLoading>
```
