### ISSUE TITLE
Use transition-group with filter

### ISSUE THREAD

**Issue by marceloavf** [PeachScript/vue-infinite-loading#62]
I'm with a problem when I try to use vue-infinite-loading with transition-group and filter, here is the situation:

Basically I get all the data from an emails array and print it in here:
```
        <transition-group name="list" mode="out-in">
            <li v-for="(email, index) of emails" :key="email" :data-index="index">
              <a>
                <card-email :who="email.Emitente" :when="email.DataMensagem" 
                  :isNew="!email.Visualizado" :cod="email.CodigoPostagem" :isSelected="emailsClicked.CodigoPostagem" @click.native="showMessage(email)">
                  <div class="title" slot="title">{{ email.Titulo }}</div>
                </card-email>
              </a>
            </li>
          </transition-group>
          <infinite-loading :on-infinite="onInfinite" spinner="waveDots" ref="infiniteLoading"></infinite-loading>
```

Here I get all the data from API and concat inside emails:
```
  onInfinite() {
      this.service.getNotification({
        CodigoUsuario: this.codigoUsuario,
        TipoLeitura: this.filterGeneral,
        RowCount: this.rowCount,
        Titulo: this.filter,
        Page: Math.floor((this.emails.length / this.rowCount) + 1),
      }).then((res) => {
        if (res.data.length) {
          this.emails = this.emails.concat(res.data);
          this.$refs.infiniteLoading.$emit('$InfiniteLoading:loaded');
          this.$nextTick(() => {
            Ps.update(this.$refs.scrollWrapper);
          });
          if (res.data.length < this.rowCount) {
            this.$refs.infiniteLoading.$emit('$InfiniteLoading:complete');
          }
        } else {
          this.$refs.infiniteLoading.$emit('$InfiniteLoading:complete');
        }
      });
    },
```

And then here is the problem, the function that filter inside a input with debounce:
```
  filterSearch: _.debounce(function filterSearch() {
      // Fallback IExplorer 11
      if (this.filterOld !== this.filter) {
        this.emails = [];
        this.$nextTick(() => {
          Ps.update(this.$refs.scrollWrapper);
          this.$refs.infiniteLoading.$emit('$InfiniteLoading:reset');
        });
        this.filterOld = this.filter;
      }
      // }
    }, 500),
```

Everything works well if I take off the transition.
As I can see, when I clean "this.emails = [];" to filter, it executes a change in transition, but I don't know if it is too fast or something like it that my "emails"  is left blank.

Anyone knows how to correct it?

Thanks!

**Comment by PeachScript** [comment]
This problem has always existed, since `v1.x`, this is the related issue #11 , but I have not found a better solution yet, do you have any idea?

**Comment by marceloavf** [comment]
I'll try to set a timeout after cleaning the emails with exactly time of the transition to let it have time to compute the next tick. 

Any other idea of what's going on?

**Comment by PeachScript** [comment]
I think `setTimeout` is not a great solution, because the coupling is too strong. Perhaps we can solve this problem through [transition hooks](https://vuejs.org/v2/guide/transitions.html#JavaScript-Hooks), but I have not found a better way to use hooks to process progression of transition.

**Comment by PeachScript** [comment]
Duplicate with #11 , in order to ensure that information is not scattered, I will close this issue, please discuss it in the #11 , thanks!
