### ISSUE TITLE
怎么把No results :(替换掉

### ISSUE THREAD

**Issue by ChasonHong** [PeachScript/vue-infinite-loading#63]
一页显示10条，接口返回只有两条，此时不是显示class='no-more'里的内容，而是显示no-results里的No results :(，这个展示体验不好，怎么修改

**Comment by PeachScript** [comment]
如果希望替换提示内容，请参阅文档中 [`slots` 部分](https://peachscript.github.io/vue-infinite-loading/#!/slots)；如果希望在你描述的情形中显示 `no-more` 的消息，请检查你的事件发送逻辑，规则是：在发送 `complete` 事件前如果前发送过 `loaded` 则会显示 `no-more`，否则会显示 `no-result`，也可以参阅文档中的[HN 示例代码](https://peachscript.github.io/vue-infinite-loading/#!/getting-started/hacker-news)。

**Comment by PeachScript** [comment]
7 天过去了仍未收到回复，默认此问题已解决，issue 我先关闭了，有需要的话可以再打开
