### ISSUE TITLE
Move getXXX functions to methods

### ISSUE THREAD

**Issue by jun9358** [PeachScript/vue-infinite-loading#64]
I want to override functions(getScrollParent, getCurrentDistance) using extends options (http://vuejs.org/v2/api/#extends)
(For non-scrolling iframe support - use scrollParent to iframe's parent body, but i think this is not good idea support it basically in this library)

So, could you move these functions to vuejs' methods?

**Comment by PeachScript** [comment]
Sounds a good idea! I will move functions to methods in the next version. For now, [this part](https://peachscript.github.io/vue-infinite-loading/#!/getting-started/with-3rd-party-scroll-plugin) of the documentation maybe useful for you.

**Comment by jun9358** [comment]
I forked and moved those functions, and using it now.
Thank you for accepting my suggestion.

**Comment by PeachScript** [comment]
Hi @jun9358 , [v2.2.0](https://github.com/PeachScript/vue-infinite-loading/releases/tag/v2.2.0) has been released, include this change, you can try it now, please feedback to here if you find any problem, thanks :D

**Comment by jun9358** [comment]
PERFECT! @PeachScript , thanks~
