### ISSUE TITLE
Is able to change each css through the click event?

### ISSUE THREAD

**Issue by Akari1987** [PeachScript/vue-infinite-loading#65]
Thank you for a wonderful plugin.
Is it possible to change each element's css through the click event?
I was able to pass each property, but I can't change each css. all css will change.
https://jsfiddle.net/akariozora/2xwph1yj/5/
sorry my wrong English. Best regards.

**Comment by jun9358** [comment]
It's not this plugin's issue.

you should put the `active` variable on each item(item object) not global scope for control each css.

So, try change a little. i wish it help you.
https://jsfiddle.net/2xwph1yj/6

**Comment by Akari1987** [comment]
@jun9358  Thank you very much. It's very helpful!!!

**Comment by Akari1987** [comment]
I thought about another css managemant, so I will write.
When each item can't be added variable (ex. api or so)
https://jsfiddle.net/akariozora/vzas0qko/3/
