### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by coderdiaz** [PeachScript/vue-infinite-loading#66]
Works with Vue 2.4.1? Please support for this version.
Thanks =)

![image](https://user-images.githubusercontent.com/1901273/28428349-c798c63a-6d3e-11e7-9b8b-e631eae2194a.png)

**Comment by PeachScript** [comment]
It can work with `Vue` 2.4.1, example is [here](https://jsfiddle.net/jamuq570/). So did you forgot passing `on-infinite` property?

**Comment by PeachScript** [comment]
1 month has passed but no reply, I will close this issue, you can reopen it if you need in the future.
