### ISSUE TITLE
类似于一个页面有四个tab页 我想用四个vue-infinite-loading组件，但是会有冲突

### ISSUE THREAD

**Issue by axy541877028** [PeachScript/vue-infinite-loading#67]
我监视第四个tab页面，一进入页面第四个tab页的vue-infinite-loading会一步步执行代码（此刻我什么也没干，照理说不会触发滚动事件）

**Comment by PeachScript** [comment]
此组件会在 `mounted` 阶段去寻找滚动父级容器并且开始计算距离，无论用户有没有进行操作；所以如果是四个 Tab 的话建议你采用如下两种方式其中之一进行处理：

1. 如果四个 Tab 的布局结构相差不大，建议公用一个 `infinite-loading` 组件，使用 `reset` 事件配合 Tab 切换，如同 demo 中的 [use with filter](https://peachscript.github.io/vue-infinite-loading/#!/getting-started/with-filter)；
2. 使用 `v-if` 控制 `infinite-loading` 组件的渲染，如果没有切换到当前 Tab，则移除该元素。

**Comment by axy541877028** [comment]
非常感谢！问题得到了解决，又学会一招，嘿嘿

**Comment by PeachScript** [comment]
不客气 : )

**Comment by axy541877028** [comment]
你的组件写的非常不错，我可以提讲个建议么？1首次没必要画圈圈直接展示10个数据，（因为首次我感觉用别的给用户提示延迟加载更好，对于你这个组件可控性更高）2定时器加载终究不是最好的办法，感觉可以设个开始时间给个阀门控制首次加载，然后执行你的mouned之后的事件

**Comment by PeachScript** [comment]
感谢你的建议。第一点取决于使用者如何控制页面渲染，和组件无关；第二点不太能理解，这个组件并未用到定时器去加载数据。

如果有新的问题请另开一个 issue 讨论，此 issue 本身的问题既然已经解决，我就先关闭了。
