### ISSUE TITLE
初始化页面，发送请求未返回结果，请求一直发送

### ISSUE THREAD

**Issue by sevensun1213** [PeachScript/vue-infinite-loading#68]
初始化页面，发送请求未返回结果，请求一直发送，而且页数一直在增加

**Comment by zzmm1** [comment]
不是vue-infinite-loading的问题吧。

**Comment by PeachScript** [comment]
应该与 #55 是同一个问题，目前还没解决，请移步 #55 进行讨论，这个 issue 我先关闭了。

@sevensun1213 如果可以的话，麻烦在 [JSFiddle](https://jsfiddle.net) 上对你遇到的问题进行重现，这样有助于我定位真正的原因，十分感谢。
