### ISSUE TITLE
Keep getting an 'Attribute is ignored on component  because the component is a fragment instance' error

### ISSUE THREAD

**Issue by weislanes** [PeachScript/vue-infinite-loading#7]
I'm pulling it from NPM and using it as per the instructions. Any ideas?

**Comment by PeachScript** [comment]
I guess you used `vue-router` in your project, and the current routing's template missing a root node, so `Vue` will throw the `fragment instance` error. You can get more information about `fragment instance` from [here](https://vuejs.org/guide/components.html#Fragment-Instance).

If the above solution cannot solve your problem, please paste your key code here.

**Comment by PeachScript** [comment]
A week passed and no reply, I will close the issue, you can reopen it if you need. @weislanes

**Comment by julianfox** [comment]
I got the same error with this template:

<template>
    <div class="reader">
        <template v-for="item in items">
            <template v-if="container.origin_file" v-html="item.content"></template>
            <template v-else>
                <div class="item">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <h2>
                                {{ item.title }}
                            </h2>
                            <div class="content" v-html="item.content"></div>
                        </div>
                    </div>
                </div>
            </template>
        </template>
        <infinite-loading :on-infinite="onInfinite" ref="infiniteLoading"></infinite-loading>
    </div>
</template>

**Comment by ghprod** [comment]
Same here,

i use it with onsen ui and already wrapped it inside `ons-page`

**Comment by ghprod** [comment]
Seems like i need to define on each component, if i register as global component, then i will get that error ..

Thanks
