### ISSUE TITLE
数据接收完成以后，会执行completed，再次下拉是否可以触发刷新

### ISSUE THREAD

**Issue by li-zemin** [PeachScript/vue-infinite-loading#70]
在使用中会出现这样的情况，就是我接受了一个列表的数据，此时已经执行了completed函数。同时对这个页面使用了keep-alive，然后重新回到这个页面后，想通过下拉再次执行infinite函数，想服务器请求数据。请问，该控件是否具备这样的功能？

**Comment by PeachScript** [comment]
`completed` 意味着数据已经全部加载完成，滚动事件会被解绑，此时无论如何都无法通过下拉触发 `on-infinite` 函数；如果希望回来以后还能继续触发，建议采用语义上更加明确的 `loaded`（意味着未来还会有数据），或者传播 `reset` 事件将组件重新激活（此做法会立即尝试触发一次加载）

**Comment by li-zemin** [comment]
好的，谢谢啦~~~辛苦辛苦~

**Comment by PeachScript** [comment]
不客气
