### ISSUE TITLE
After the page is loaded, onInfinite function is called two times

### ISSUE THREAD

**Issue by aisin** [PeachScript/vue-infinite-loading#71]
No matter `direction="top"` or `direction="bottom"`, `onInfinite` will be called two times, and I reset `scrollTop` of the scroll parent, but it's not working for the problem.

**Comment by PeachScript** [comment]
Could you reproduce it on the [JSFiddle](https://jsfiddle.net)?

**Comment by mauricemojito** [comment]
Hm, getting exactly the same...

**Comment by mauricemojito** [comment]
https://jsfiddle.net/ohhf3La7/

**Comment by PeachScript** [comment]
@mauricemojito I cannot running your example, did I missing something? And...why did you already use the `force-use-infinite-wrapper` attribute? I have not complete this feature now...

**Comment by mauricemojito** [comment]
Oh, I thought It was completed. Do you use only the getMessages() function or the complete Instance ?

**Comment by PeachScript** [comment]
No, I just run it on the `JSFiddle` but it throw import error in the console, can you run it on the `JSFiddle`?

The new feature will be released with the next version, but now, if you want to implement the same feature, you need to set the scrollParent manually like this way: `this.$refs.infiniteLoading.scrollParent = yourRealScrollParent`.

**Comment by mauricemojito** [comment]
Ah, I found my mistake. I used methods and the created hook together, therefore it's called twice.

**Comment by PeachScript** [comment]
No updates, so I will close it.
