### ISSUE TITLE
Example for direction='top' ?

### ISSUE THREAD

**Issue by asafyish** [PeachScript/vue-infinite-loading#73]
Hi,

I am trying to use infinite loading with direction='top', but I don't understand how to update scrollTop ? Is there an a working example with direction='top' that I can see ?

template:
```vue
  <div v-else>
    <infinite-loading ref="infiniteLoading" :on-infinite="onInfinite" direction="top"/>
    <component v-for="row in rows" :is="row.type" :key="row.key" />
  </div>
```
js:
```js
    onInfinite() {
      if (this.size >= this.rows.length) {
        this.$refs.infiniteLoading.$emit('$InfiniteLoading:complete');
      } else {
        this.size += 20;
       this.$refs.infiniteLoading.$emit('$InfiniteLoading:loaded');
       // TODO Need to update scrollTop, but to what value ? and for which item ?
      }

```
because I am not updating scrollTop, the function onInfinite is called multiple times, and the entire data set is loaded (just like the docs warn about).

**Comment by PeachScript** [comment]
Imagine we have 10 items in the list, let us call the top item as `A`, then it will insert another 10 items in the top when we scroll to top, we call the top item as `K` at present. Now, the `K` will display in the top of the list, that is to say, we missed the items `B` ~ `J`, so we should scroll to the `A` automatically after items be shifted, then we can read the `B` ~ `J` items through scroll up. The process of scroll to `A`, we call it `update scrollTop`.

Sounds a little intricate, I don't know whether it is clear.

**Comment by mauricemojito** [comment]
Here's some help:
1)In your onInfinite method add:
`this.height = this.$refs.scrollWrapper.scrollHeight`
2)Define your wrapper:
`<div class="msg-layout" ref="scrollWrapper" infinite-wrapper >`
`<infinite-loading :on-infinite="getMessages" spinner="spiral" direction="top" ref="infiniteLoading"></infinite-loading>`
**Your Loop**
`</div>`
3)Declare your render data:
`height: 0`
4)Not let's create a watcher to get the old and new value for the height:

       watch: {
               oldHeight: function(newVal,oldVal){


                var diff = newVal - oldVal;

                this.$refs.scrollWrapper.scrollTop = diff

            }
        },
5) Now, when you scroll, you'll stay at the same position
Some extra tips for getting data from you server:
Use lodash in a computed method, to sort it by id(On my server, I use Laravel and the paginate method)
`return lodash.orderBy(this.messages, 'id', ['asc'])`

**Comment by asafyish** [comment]
I was able to solve it a bit differently:
```js
    onInfinite() {
      // this.rows have ALL the rows, but we don't 
      // want to render all of them unless the user scroll to them
      if (this.size >= this.rows.length) {
        this.$refs.infiniteLoading.$emit('$InfiniteLoading:complete');
      } else {
        this.size += 20; // this.size is the amount of rows we want to render
        // this is the magic line
        this.$refs.infiniteLoading.scrollParent.scrollTop = this.$refs.infiniteLoading.scrollParent.offsetHeight;
        this.$refs.infiniteLoading.$emit('$InfiniteLoading:loaded');
      }
    }
```

**Comment by shyam528** [comment]
It's not working, can you please  help me?

**Comment by PeachScript** [comment]
@shyam528 sure, before that, you should provide a live demo to reproduce your problem.

**Comment by imkimchi** [comment]
Literally nothing here worked so had to fix it on my own.
here's the code

```js

async onInfinite ($state) {
    let height = this.$refs.infiniteLoading.scrollParent.scrollHeight // this
    let res = await this.loadMoreChat()

    if(!res) {
      $state.complete()
    } else {
      //these lines works
      let el = this.$refs.infiniteLoading.scrollParent // this
      el.scrollTop = el.scrollHeight - height; //this
      $state.loaded()
    }
  } else {
    $state.complete()
  }
}
```
