### ISSUE TITLE
Pass arguments for the on-infinite function

### ISSUE THREAD

**Issue by vlahde** [PeachScript/vue-infinite-loading#75]
Hello, I have a page that includes a few smaller lists of movies. I ran into a problem when trying to implement on-infinite callback function:

This throws "TypeError: Cannot read property 'call' of undefined":
`<infinite-loading :on-infinite="getMicroList('releases')" ref="releases" spinner="circles">`

while this is ok:
`<infinite-loading :on-infinite="getMicroList" ref="releases" spinner="circles">`

Are multiple lists even possible on the same page without having to copy all the callback function code over and over again?

**Comment by PeachScript** [comment]
You can use `bind` method:

```html
<infinite-loading :on-infinite="getMicroList.bind(null, 'releases')" ref="releases" spinner="circles">
```

Exactly, it is not the best practice, I will change the type of `on-infinite` to event in the next version, we will can use it like the official event listener `@click`:
```html
<infinite-loading @infinite="getMicroList('releases')" ref="releases" spinner="circles">
```

**Comment by vlahde** [comment]
Thank you so much for the help and for the great component!

**Comment by PeachScript** [comment]
@vlahde you're welcome :P

**Comment by PeachScript** [comment]
Hi @vlahde  , [v2.2.0](https://github.com/PeachScript/vue-infinite-loading/releases/tag/v2.2.0) has been released, include the `infinite` event change, you may need update the way to bind `infinite` function, document is [here](https://peachscript.github.io/vue-infinite-loading/#!/events), please feedback to here if you find any problem, thanks :D

**Comment by vlahde** [comment]
Works like a charm! I also love the new state system. Thanks again for the great component, man!

**Comment by PeachScript** [comment]
Thanks for your appreciation!

Best regards.
