### ISSUE TITLE
How to use this component with multi lists in tabs?

### ISSUE THREAD

**Issue by ufosky** [PeachScript/vue-infinite-loading#77]
I have try to use this component in my project, but the `on-infinite` handler has no argument for distinct which one trigger the event if multi lists exist.

**Comment by PeachScript** [comment]
Same as #75 ?

**Comment by ufosky** [comment]
I use `aFunction.bind(null, anArgument)` for passing argument, now the method can get the argument, but now another issue for using this component in tabs.
When I scroll the page to bottom, it always trigger all the lists in tabs loading more data, but I want only the list in the visible tab loading more data.

**Comment by PeachScript** [comment]
Perhaps you can use the same `InfiniteLoading` component in all tabs, and load different data through a variable like `type`.

**Comment by PeachScript** [comment]
No updates, I will close this issue, you can reopen it if you need in the future.

**Comment by PeachScript** [comment]
Hi @ufosky , I have been released a new version [`v2.2.1`](https://github.com/PeachScript/vue-infinite-loading/releases/tag/v2.2.1) to disable attempt load when this component is invisible, maybe it is useful for you.

Related issue: #93

**Comment by oroalej** [comment]
Hi @PeachScript, how to enable the attempt load when the component is visible ( initially it was hidden ). The vue-infinite-loading only works when I start to scroll.
