### ISSUE TITLE
Distance from the TOP

### ISSUE THREAD

**Issue by nikolaynesov** [PeachScript/vue-infinite-loading#8]
Is there a way to set the distance from the top (not only bottom).
Unfortunately I have not find it here
https://peachscript.github.io/vue-infinite-loading/#!/properties
Are you going to implement this in nearest future?

**Comment by PeachScript** [comment]
Sorry, this component cannot support that for the moment. But through this issue, I think I should to add it in the next version. 

Before that, I hope you can describe the usage scene for me. For example, whether we need to scroll to top infinitely and scroll to bottom infinitely in a same case? It is very useful for me to add the new feature, thanks!

**Comment by PeachScript** [comment]
In my mind, we need to pull down or pull up to load another page rather than scroll down or scroll up directly when using some apps, so I will close this issue until I found some situations that really needed the feature in this component.
