### ISSUE TITLE
"You are using the runtime-only" Warning on version 2.2.0

### ISSUE THREAD

**Issue by asafyish** [PeachScript/vue-infinite-loading#83]
### Version
2.2.0

### Vue.js version
2.4.4

### What is exptected?
To not get this warning, as it was in version 2.1.3

### What is actually happening?
I am getting a warning:
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

found in

---> <Anonymous>
       <InfiniteLoading>

### How to repreduce this problem?
Create a version using:
```bash
vue init webpack my-project
```
with runtime-only configuration.

**Comment by syn-zeta** [comment]
That error is unrelated to this component (you will see the same warning even with v2.1.3 if you don't change anything else). [Here](http://lmgtfy.com/?q=%5BVue+warn%5D%3A+You+are+using+the+runtime-only+build+of+Vue).

**Comment by asafyish** [comment]
@syn-zeta I am aware of this vue behavior and that's not the case.
I verified multiple times, on versoin 2.2.0 I am getting the warning, on version 2.1.3 I am not - nothing else changed.

**Comment by asafyish** [comment]
I am actually pretty sure it's from commit https://github.com/PeachScript/vue-infinite-loading/commit/6168c31961e0c0d744b6ebdcaf0e37b40da048b3.

**Comment by syn-zeta** [comment]
My bad for the wrong assumption. Moving out the spinners to its own component in a `.vue` file should fix this issue (and also reduce the bloat in the main component).

**Comment by PeachScript** [comment]
My mind is the spinners just need a template, so use the [local registration](https://vuejs.org/v2/guide/components.html#Local-Registration) may be better, is this problem caused by the local registration of component?

**Comment by asafyish** [comment]
The warning is happening on usage, not on registration. I am registering infinite-loader just once, globally, in my main.js:
```js
import VueVirtualScroller from 'vue-virtual-scroller/dist/vue-virtual-scroller';
Vue.use(VueVirtualScroller);
```

And then, each time I am using a component with <infinite-loading> I am getting the warning.

**Comment by Jussiadev** [comment]
#87

**Comment by Jussiadev** [comment]
@asafyish Hey. I have the same problem. Have you found a solution?

**Comment by PeachScript** [comment]
@Jussiadev @asafyish you can use `Runtime + Compiler` build of `Vue.js` to solve this temporarily, and could you tell me the reason that you want to the `Runtime-only` build of `Vue.js`?

**Comment by asafyish** [comment]
@PeachScript I was mistaken. I am registering vue-infinite-loading in a local component, not global and still getting the warning.

@Jussiadev No solution so far. The right solution is probably a fix in the library itself.

**Comment by Jussiadev** [comment]
@PeachScript why this happens even I use your base example

**Comment by PeachScript** [comment]
@asafyish @Jussiadev perhaps I did not make it clear.

This component use the local registration component as the spinners, and the local registration component was not be pre-compiled when this component be released, but your project use the `Runtime-only` build version of `Vue.js`, it does not include the template compiler, the warning will be thrown when the `Vue.js` try to render a uncompiled template.

So there has a temporary solution to solve it, just change your `Vue.js` version from `Runtime-only` to `Runtime + Compiler`, simply to do it in your `webpack` configurations:
```js
...
resolve: {
  alias: {
    'vue$': 'vue/dist/vue.esm.js'
  }
}
...
```

**Comment by asafyish** [comment]
@PeachScript Yeah that's a great temporary solution, but long-term, I think it's better not to mandate including the compiler in addition to the runtime.

**Comment by PeachScript** [comment]
@asafyish of course! I will replace all spinners templates with the compiled templates in the next version.

**Comment by PeachScript** [comment]
Hi @asafyish @Jussiadev , the new version [`v2.2.1`](https://github.com/PeachScript/vue-infinite-loading/releases/tag/v2.2.1) has been released, includes this fix, you can try it now.

**Comment by Jussiadev** [comment]
@PeachScript Thank you so much.
Sorry, that is off topic, but how to hide the spinner

**Comment by PeachScript** [comment]
@Jussiadev it does not matter, they are same problem.

You can create a empty element to hide the spinner through `slot` feature.

**Comment by asafyish** [comment]
Can verify that it's working correctly in 2.2.1.

**Comment by Jussiadev** [comment]
@PeachScript Does not help

```
<infinite-loading @infinite="infiniteHandler" spinner="circle">
                <span slot="slot"></span>
            </infinite-loading>
```

**Comment by asafyish** [comment]
Do you mean 
```html
<infinite-loading @infinite="infiniteHandler" spinner="circle">
  <span slot="spinner"></span>
  </infinite-loading>
```

**Comment by Jussiadev** [comment]
@asafyish Thank you. Now it works
