### ISSUE TITLE
`loaded` event without this.$refs

### ISSUE THREAD

**Issue by ankurk91** [PeachScript/vue-infinite-loading#84]
### Version
2.2

### Vue.js version
2.4.2

### What is expected?
Allow `reset` to be emitted outside of handler but without  `$srefs`.
Since you have depreciated the events by `ref`; how do i emit `reset` event without `refs`

Next line giving warning in console.
```js
// This works fine in v2.2
 this.$refs.infiniteLoader.$emit('$InfiniteLoading:reset');
```
I could not find any documentation about this.

**PS.**
Now i am asking about `loaded` event

**Comment by syn-zeta** [comment]
What is the warning that you're noticing? The component does not print any warning for emitting a reset event using a reference, nor with the new `$state.reset()` way.

**Comment by ankurk91** [comment]
Warning is coming from this line of code -
https://github.com/PeachScript/vue-infinite-loading/blob/0e428c4b21562298971570b7d4f14c16671b89c1/src/components/InfiniteLoading.vue#L66

My concern is not about the warnings, i am talking the depreciation of  events emitted by `ref`.
I don't want to use deprecated methods in my code.

**Comment by syn-zeta** [comment]
Emitting `reset` using a reference is not deprecated, which is why the warning only mentions and complains on loaded and completed events. To fix the warnings on those, please refer to the release notes at https://github.com/PeachScript/vue-infinite-loading/releases/tag/v2.2.0.

**Comment by ankurk91** [comment]
Oh i see,
In my case i have to call `loaded` event in mounted hook to let infinite loader know that i have some items pre-loaded.

```js
 mounted() {   
      // Tell infiniteLoading component that we already have initial items loaded
      this.$refs.infiniteLoader.$emit('$InfiniteLoading:loaded');
    },
```
Is there any other way to emit `loaded` event ?

**Comment by syn-zeta** [comment]
`this.$refs.infiniteLoading.stateChanger.reset()`
`this.$refs.infiniteLoading.stateChanger.loaded()`
`this.$refs.infiniteLoading.stateChanger.complete()`

Not sure if this is the best way to handle things, though, as it accesses internal state directly.
