### ISSUE TITLE
Remove dependency on less

### ISSUE THREAD

**Issue by HeuHax** [PeachScript/vue-infinite-loading#86]
It seems a bit pointless to depend on less and less-loader for such a small amount of css.

Instead css should be pulled out of the component and bundled as plain css, so we don't need less if we prefer sass or plain old css.

**Comment by syn-zeta** [comment]
The component only has less as a dev dependency, which doesn't affect the regular users. What did you mean by "so we don't need less if we prefer sass or plain old css"?

**Comment by PeachScript** [comment]
No updates, I will close this issue, you can reopen it if you need in the future.
