### ISSUE TITLE
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

### ISSUE THREAD

**Issue by Jussiadev** [PeachScript/vue-infinite-loading#87]
### Version
2.2.0

After updating the vue-infinite-loading, an error occurred in the browser, even if I completely use your example. Also in the basic example of the spinner is not visible

**Comment by PeachScript** [comment]
Duplicate with #83 , please discuss in that, closed.
