### ISSUE TITLE
Uncaught (in promise) TypeError: res.json is not a function

### ISSUE THREAD

**Issue by unssnu** [PeachScript/vue-infinite-loading#92]
### "vue": "^2.4.2",

Hello,

 I used the "Use with filter" example in docs, while the console throw a mistake that ：Uncaught (in promise) TypeError: res.json is not a function

Would you please help with this issue? thanks!
Below is my code:

infiniteHandler($state) {
        axios.get(baseUrl + '/car/getCarList', {
          params: {
            pageNum: 1,
            pageSize: 100,
            cityId: getCookie('cityId'),
            orderflag: "default",
            orderType: "asc",
            car_brand_id:'',
            recharge_mileage:'',
            price:'',
            car_level:'',
            page: this.carlist.length / 20 + 1,
          },
        }).then(res => res.json()).then((data) => {
          if (data.hits.length) {
            this.carlist = this.carlist.concat(data.hits);
            $state.loaded();
            if (this.carlist.length / 20 === 10) {
              $state.complete();
            }
          } else {
            $state.complete();
          }
        });
      },
      changeFilter() {
        this.carlist = [];
        this.$nextTick(() => {
          this.$refs.infiniteLoading.$emit('$InfiniteLoading:reset');
        });
      },
    },

**Comment by PeachScript** [comment]
Sorry, it's my mistake. The `res.json()` method is the way to transform response data to `JSON` of the `vue-resource`, but `axios` support automatic transform so we don't need that.

You can checkout the [new document](https://peachscript.github.io/vue-infinite-loading/#!/getting-started/with-filter).
