### ISSUE TITLE
Multiple infinite-loading on page

### ISSUE THREAD

**Issue by vutrongvu** [PeachScript/vue-infinite-loading#94]
I am a beginner in vue. Now I used two vue-infinite-loading in two tab html. But when i test on mobile i saw double request when scroll page.

**Comment by PeachScript** [comment]
You should to provide more information base on the [issue template](https://github.com/PeachScript/vue-infinite-loading/blob/master/.github/ISSUE_TEMPLATE.md)

**Comment by MoraesGil** [comment]
Well in my case i guess is the same of vutrongvu.

I have a component to list users using infinite-loading and i repead calling of this component
`<gm-my-component title="A"/>
<gm-my-component title="B"/>
`

the first works fine, but the B loadMore 2 times and no scrool more, both have same array list source

**Comment by PeachScript** [comment]
@MoraesGil could you reproduce it on [JSFiddle](https://jsfiddle.net)?

**Comment by MoraesGil** [comment]
Hi I can but I’m at work now, at home I do,
This issue occurred when I’m trying do list of roles, Users and users_roles
(print in Portuguese)


Another issue is that when I move with vue-draggable the scroll not update
but is another challange


Em ter, 26 de set de 2017 às 12:36, Peach <notifications@github.com>
escreveu:

**Comment by vutrongvu** [comment]
Related issue: #93 
I will close this issuse.
Thanks :+1:

**Comment by kaisanjay** [comment]
> infinite-wrapper

can you please provide the snippet.
