### ISSUE TITLE
$state.loaded() is not a function

### ISSUE THREAD

**Issue by SirCumz** [PeachScript/vue-infinite-loading#96]
### Version
v2.2

### Vue.js version
2.x

### What is expected?
$state.loaded should be a function

### What is actually happening?
errors $state.loaded() is not a function

### How to reproduce this problem?
Simple use the v2.2 script

**Comment by PeachScript** [comment]
I cannot reproduce it, could you reproduce it on [JSFiddle](https://jsfiddle.net)?

**Comment by PeachScript** [comment]
No update, I will close this issue, you can reopen it if you need in the future.
